let answerBtn = document.getElementById("theAnswer");
let stars = document.getElementById("stars");
let answers = document.getElementById("answers");
let answerBox = document.getElementById("answer-box");
let i = 0;
let helloSection = document.querySelector('.hello');


setTimeout(() => {
    helloSection.style.opacity = '0';
    helloSection.style.display = 'none';
}, 3000);

// Words that marked With starts
let WithStar = "Regio frontalis / Frons*-Regio mentalis / Mentum*-Thorax, Steth / Pectus*-Costa(e)*-Dorsum / Regio Dorsalis*-Venter, Abdomen / ventral*-Regio epigastrica, Epigastrium / epigastrisch*-Axilla*-Brachium*-Antebrachium*-Cubitus*-Articulatio cubiti*-Fossa*-Manus*-Dorsum manus*-Digitus(Digiti) manus*-Pollex, Digitus manus I*-Annularius, Digitus manus IV*-Phalanx(Phalangen) (proximalis,    media, distalis)*-Unguis / Unguis incarnatus / subungual* -Pelvis*-Calcis*-Planta pedis, Planta*-Digitus(Digiti) pedis / Digitus malleus*-Os(Ossa)*-Ostitis*-Extremität(en)*-Bursa synovialis*-Vagina synovialis tendinis*-Cranium*-Os frontale*-Lobus*-Lobus frontalis*-Os parietale*-Os temporale*-Processus styloideus*-Processus mastoideus*-Os occipitale / Occiput*-Os sphenoidale*-Os ethmoidale*-Os nasale*-Cartilago septi nasi*-Os zygomaticum*-Arcus zygomaticus*-Os hyoideum*-Maxilla*-Mandibula*-Vertebra / vertebral*-Processus spinosus*-Processus articularis(articulares)*-Processus costalis*-Columna vertebralis / Columna*-Vertebrae cervicales (pl.)*-Atlas (Vertebra cervicalis I)*-Axis (Vertebra cervicalis II)*-Vertebra prominens (V. cervicalis VII)*-Vertebrae thoracicae*-Vertebrae lumbales*-Vertebrae sacrales / Os sacrum*-Kauda*-Scapula*-Klavikula*-Omarthrose*-Articulatio akromioklavikularis*-Humerus / Humerusfraktur*-Caput humeri*-Olekranon*-Ulna*-Radius*-Articulatio carpometacarpalis / Articulatio carpometacarpalis I (pollicis)*-Carpus / Ossa carpi, Ossa carpalia*-Os scaphoideum*-Os lunatum*-Os pisiforme*-Ossa metacarpi, Ossa metacarpalia*-Os ilium*-Crista iliaca*-Os ischii / Tuber ischiadicum*-Os pubis*-Symphysis pubica, Symphyse*-Coxa*-Articulatio coxae*-Acetabulum*-Coxitis*-Coxarthrose*-Femur, Os femoris*-Caput femoris*-Collum femoris*-Trochlea*-Trochanter major / minor*-Meniscus*-Meniscus lateralis*-Meniscus medialis*-Gonarthrose*-Crus*-Tibia*-Caput tibiae, Plateau tibialis*-Fibula*-Malleolus lateralis*-Malleolus medialis*-Tarsus / Ossa tarsi, Ossa tarsalia*-Talus*-Calcaneus*-Os naviculare**-Os cuneiforme*-Kondylus, Kondyle*-Epikondylus, Epikondyle*-Cartilago, Chondros*-Chondritis*-Ossifikation*-Musculus pectoralis major / minor*-Musculus rectus abdominis*-Musculus gluteus maximus / minimus*-Musculus quadriceps femoris*-Ligamentum cruciatum anterius /posterius*-Ligamentum patellae*-Ligamentum inguinale*-Canalis inguinalis*-Canalis vertebralis*-Thenar*-Rigidität, Rigor / rigide*-magnus, major, maximus*-parvus, minor, minimus*-longus / brevis*-Origo / Insertio *"
let withStar2 = "Umbilicus, Omphalos*-Funiculus umbilicalis / Funiculus*-Funiculus spermaticus*-Omphalitis*-Isthmus*-Frenulum*-Mukosa*-Traumatologie / Traumatologe*-Polytrauma*-polytraumatisiert*-Vulnerabilität / vulnerabel*-Arthralgie*-Arthritis urica, Urikopathie*-Arthrose, Osteoarthrose*-Ankylose*-Pseudarthrose*-Arthroskopie*-Discus intervertebralis*-Diskusprolaps*-Lumbago, Lumbalgie*-Kyphose*-Lordose*-Skoliose*-Genu valgum*-Genu varum*-Pes equinovarus*-Pes planus*-Myalgie*-Myositis*-Vs. Myelitis*-Amyotrophie, Muskelatrophie*-Muskeldystrophie*-Myasthenie / Myasthenia gravis*-Torticollis*-Tendovaginitis, Tendosynovitis*-Osteomyelitis*-Periost*-Periostitis*-Osteoporose*-Osteom / Osteosarkom*-Fraktur*-frakturiert*-Frakturfragment / Fragment*-Dislokation*-Luxation*-Konstriktion, Striktur*-Cerebrum*-Cerebellum*-Diencephalon*-Truncus cerebri, Truncus encephali*-Pons*-Mesencephalon , Midbrain*-Cortex cerebri / Cortex*-Enzephalitis*-Cephalgie*-Medulla spinalis, Myelon*-Gyrus cerebri*-Meningen*-Dura mater*-Pia mater*-Meningitis*-Liquor cerebri / Liquor cerebrospinalis*-Hydrozephalus*-Tentorium*-Ganglion*-Plexus*-Nervus olfactorius 1*-Nervus opticus 2*-Nervus facialis 7*-Nervus phrenicus, diaphragmaticus*-Neuritis*-Radix*-Commotio / Contusio / Compressio cerebri*-Epilepsie*-Parkinson*-Spina bifida*"

// the answers
let theAnswer2 = "Nabel-Nabelschnur / dünnes Seil, Strang-Samenstrang-Nabelentzündung-Enge-Bändchen, kleine Schleimhautfalte-Schleimhaut-Unfallmedizin, Unfallheilkunde, Verletzungskunde,Wundenkunde / Unfallmediziner-Mehrfachverletzung-mehrfachverletzt-Anfälligkeit / verletzlich, verwundbar-Gelenkschmerzen-Gicht-Gelenkverschleiß, degenerative Gelenkerkrankung-Gelenkversteifung-Falschgelenk-Gelenkspiegelung-Bandscheibe, Zwischenwirbelscheibe-Bandscheibenvorfall-Hexenschuss-Wirbelsäulenkrümmung nach hinten-Wirbelsäulenkrümmung nach vorne-seitliche Wirbelsäulenkrümmung-X_Bein-O_Bein-Klumpfuß-Plattfuß-Muskelschmerzen-Muskelentzündung-Rückenmarksentzündung-Muskelschwund-Muskelschwäche, Muskelschwund-Muskelschwäche / autoimmune Muskelschwäche-Schiefhals-Sehnenscheidenentzündung-Knochenmarkentzündung-Knochenhaut-Knochenhautentzündung-Knochenschwund-gutartige / bösartige Knochengeschwulst-Knochenbruch-gebrochen-Bruchstück / Stück-Verlagerung, Fehlstellung, Versetzung, Umsetzung-vollständige Verrenkung, Ausrenkung, Auskugelung-Verengung, Einengung, Einschnürung-Großhirn-Kleinhirn-Zwischenhirn-Hirnstamm-Brücke-Mittelhirn-Großhirnrinde / Rinde-Gehirnentzündung-Kopfschmerzen-Rückenmark-Gehirnwindung-Hirn_ und Rückenmarkshäute-harte Hirnhaut-weiche, innere Hirnhaut-Hirnhautentzündung-Gehirnwasser / Gehirn_ und Rückenmarksflüssigkeit-Wasserkopf-Zelt-Nervenknoten, Überbein-Geflecht-Riechnerv-Sehnerv-Gesichtsnerv-Zwerchfellnerv-Nervenentzündung-Wurzel-Gehirn_ erschütterung / prellung / quetschung-Krampfanfall, Fallsucht, Krampfleiden-Schüttellähmung-Wirbelspalt, offene Wirbelsäule"
let theAnswer = "Stirnregion / Stirn-Kinnregion / Kinn-Brustkorb / Brust-Rippe(n)-Rücken / Rückenregion-Bauch / bauchseitig-Oberbauch, Magengrube / Oberbauch betreffend-Achselhöhle-Oberarm-Unterarm-Ellenbogen-Ellenbogengelenk-Grube-Hand-Handrücken-Finger-Daumen-Ringfinger-Finger, oder Zehenglied(Finger, oder Zehenglieder)(grundglied , mittelglied , endglied)-Nagel / eingewachsener Zehennagel / unter dem Nagel-Becken-Ferse, Hacke-Fußsohle-Zehe(n) / Hammerzehe-Knochen / Mund-Knochenentzündung-Gliedmaße(n)-Schleimbeutel, Gleitbeutel-Sehnenscheide-Schädel-Stirnbein-Lappen (Sng.)-Stirnlappen, vordere Hirnlappen-Scheitelbein-Schläfenbein-Griffelfortsatz (des Schläfenbeins)-Warzenfortsatz (des Schläfenbeins)-Hinterhauptbein / Hinterkopf-Keilbein-Siebbein-Nasenbein-Septumknorpel-Jochbein-Jochbogen-Zungenbein-Oberkiefer-Unterkiefer-Wirbel / die Wirbel betreffend-Dornfortsatz-Gelenkfortsatz(ätze)-Rippenfortsatz-Wirbelsäule / Säule-Halswirbel (pl.)-Träger, Nicker, 1. Halswirbel-Dreher, 2. Halswirbel-7. Halswirbel-Brustwirbel (pl.)-Lendenwirbel (pl.)-Kreuzbeinwirbel / Kreuzbein-Schwanz, Endstück-Schulterblatt-Schlüsselbein-Schultergelenkverschleiß-Schultereckgelenk, kleines Schultergelenk-Oberarmknochen / Oberarmbruch-Oberarmknochenkopf-Ellenbogenspitze-Elle-Speiche-Handwurzel,Mittelhand,Gelenk / Daumensattelgelenk-Handwurzel / Handwurzelknochen-Kahnbein-Mondbein-Erbsenbein-Mittelhandknochen-Darmbein-Darmbeinkamm-Sitzbein / Sitzbeinhöcker-Schambein-Schambeinfuge-Hüfte, Hüftregion-Hüftgelenk-Hüftgelenkspfanne-Hüftgelenkentzündung-Hüftgelenkverschleiß-Oberschenkel, Oberschenkelknochen-Oberschenkelkopf, Hüftkopf-Oberschenkelhals-Rolle, Rollknorpel, Walze, Flaschenzug-großer / kleiner Rollhügel-scheibenförmiger Kniegelenkknorpel-Außenmeniskus-Innenmeniskus-Kniegelenkverschleiß-Unterschenkel, Schenkel, Bein-Schienbein-Schienbeinkopf-Wadenbein-Außenknöchel-Innenknöchel-Fußwurzel / Fußwurzelknochen-Sprungbein-Fersenbein-Kahnbein-Keilbein-Gelenkkopf, Knochengelenk, Gelenkknöchel-Gelenkhöcker-Der Knorpel-Knorpelentzündung-Verknöcherung-großer / kleiner Brustmuskel-gerader Bauchmuskel-großer / kleiner Gesäßmuskel-vierköpfiger Oberschenkelmuskel-vorderes / hinteres Kreuzband-Kniescheibenband, Kniescheibensehne-Leistenband-Leistenkanal-Wirbelkanal, Rückenmarkskanal-Daumenballen-Steifigkeit, Starrheit, Starre / steif, starr-groß-klein-lang / kurz-Ursprung, Muskelursprung / Ansatz, Muskelansatz"

// creat arrays
let starsArr = WithStar.split("-");
let answersArr = theAnswer.split("-");
let withStar2Arr = withStar2.split("-");
let theAnswer2Arr = theAnswer2.split("-");
let totalStar = starsArr.concat(withStar2Arr);
let totalAnswer = answersArr.concat(theAnswer2Arr);

// to creat random word wich marked with stars
function pickOneWord() {
    // creat random number
    let randomNumber = Math.floor(Math.random() * 201);
    // put the random word from the stars Array
    stars.innerHTML = totalStar[randomNumber];
    // choos the same number of answers Array
    answers.innerHTML = totalAnswer[randomNumber];
    // hide the answer box
    answers.style.display = "none";
    // To Make Write Box Empty Agaon
    answerBox.value = "";
    // reset i value and return color and button value
    i = 0
    answerBtn.style.background = "#0d6efd";
    answerBtn.innerHTML = "Check The Answer";
}

// to chick the answers
function gitTheAnswe() {
    // increasing i value
    i++;
    let answerText = answerBox.value;
    let chikingTxt = answers.innerHTML;
    // chicking the answers
    if (answerText == "") {
        answers.style.display = "none";
    } else if (chikingTxt.includes(answerText) || i === 3) {
        answers.style.display = "block";
        answerBtn.style.background = "green";
        answerBtn.innerHTML = "Right Answer";
    }
    // change button color
    if (i === 1 & answerText !== "" & chikingTxt.includes(answerText) == false) {
        answerBtn.style.background = "red";
        answerBtn.innerHTML = "Wrong Answer Try Again";
    } else if (i === 2 & answerText !== "") {
        answerBtn.style.background = "green";
        answerBtn.innerHTML = "Show The Right Answer";
    } 
}
//  Text To Speach API 
let soundBtnAnswer = document.getElementById('sound');
soundBtnAnswer.addEventListener("click", () => {
    if (answers.style.display == "block") {
        // the SpeechSynthesisUtteranc is a Web Speach  API That represents a speach request
    let utterance = new SpeechSynthesisUtterance(answers.innerText);
    // Change The language of speaker 
    // utterance.voice = window.speechSynthesis.getVoices()[3];

    // Set the language to German
    utterance.lang = "de-DE";
    // Set the voice to a German voice
    var germanVoice = speechSynthesis.getVoices().filter(function(voice) {
        return voice.lang === 'de-DE';
        })[0];
    utterance.voice = germanVoice;

    // speak method of speechSynthesis speak the utterance
    speechSynthesis.speak(utterance); 
    } else {
        return false;
    }
        
})
let soundBtn = document.getElementById('question-sound');
soundBtn.addEventListener("click", () => {
    // the SpeechSynthesisUtteranc is a Web Speach  API That represents a speach request
    let utterance = new SpeechSynthesisUtterance(stars.innerText);
    // Change The language of speaker 
    // utterance.voice = window.speechSynthesis.getVoices()[3];
     // Set the language to German
     utterance.lang = "de-DE";
     // Set the voice to a German voice
     var germanVoice = speechSynthesis.getVoices().filter(function(voice) {
         return voice.lang === 'de-DE';
         })[0];
     utterance.voice = germanVoice;
    // speak method of speechSynthesis speak the utterance
    speechSynthesis.speak(utterance); 
})

// Speach To Text
const recordBtn = document.querySelector(".record"),
  result = document.querySelector(".result"),
  downloadBtn = document.querySelector(".download"),
  inputLanguage = document.querySelector("#language"),
  clearBtn = document.querySelector(".clear");

let SpeechRecognition =
    window.SpeechRecognition || window.webkitSpeechRecognition,
  recognition,
  recording = false;

function speechToText() {
  try {
    recognition = new SpeechRecognition();
    recognition.lang = "de";
    recognition.interimResults = true;
    recordBtn.querySelector("p").innerHTML = `<i class="fa-solid fa-microphone-slash"></i>`;
    recordBtn.style.background = "#0b5ed7";
    recordBtn.style.color = "#fff";
    recognition.start();
    recognition.onresult = (event) => {
      const speechResult = event.results[0][0].transcript;
      //detect when intrim results
      if (event.results[0].isFinal) {
        result.innerHTML += " " + speechResult;
      } else {
        //creative p with class interim if not already there
        if (!document.querySelector(".interim")) {
          const interim = document.createElement("p");
          interim.classList.add("interim");
          result.appendChild(interim);
        }
        //update the interim p with the speech result
        answerBox.value = speechResult;
      }
    };
    recognition.onspeechend = () => {
      speechToText();
    };
    recognition.onerror = (event) => {
      stopRecording();
      if (event.error === "no-speech") {
        alert("No speech was detected. Stopping...");
      } else if (event.error === "audio-capture") {
        alert(
          "No microphone was found. Ensure that a microphone is installed."
        );
      } else if (event.error === "not-allowed") {
        alert("Permission to use microphone is blocked.");
      } else if (event.error === "aborted") {
        alert("Listening Stopped.");
      } else {
        alert("Error occurred in recognition: " + event.error);
      }
    };
  } catch (error) {
    recording = false;
    console.log(error);
  }
}

recordBtn.addEventListener("click", () => {
  if (!recording) {
    speechToText();
    recording = true;
  } else {
    stopRecording();
  }
});

function stopRecording() {
  recognition.stop();
  recordBtn.querySelector("p").innerHTML = `<i class="fa-solid fa-microphone"></i>`;
  recordBtn.style.background = "#0d6efd";
  recordBtn.style.color = "#fff";
  recording = false;
}
// Pick Random Word section

let randomWords1 = "Schläfenregion#Luftröhrenentzündung#Tracheoskopie*#Luftröhrenspiegelung#Tracheotomie*#Luftröhrenschnitt#Tracheomalazie#Luftröhrenerweichung#Tracheostoma#bronchial#Fußwurzel#Fußwurzelknochen#Talus*#Schläfe#Truncus#Torso#Rumpf#Körperstamm#Stamm#Rumpf#Körperstamm#Thorax#Steth-#Pectus*#Brustkorb#Brust#Sternum*#Brustbein#Processus xiphoideus#Processus ensiformis#Processus#Xiphoid*#Schwertfortsatz#Fortsatz#Schwert#Costa(e)*#Rippe(n)#intercostal#zwichen den Rippen#Dorsum#Regio Dorsalis*#Rücken#Rückenregion#Venter#Abdomen#ventral*#Bauch#bauchseitig#Regio epigastrica#Epigastrium#epigastrisch*#Oberbauch#Magengrube#Nabelregion#Regio lumbalis#Lendenregion#Lendenbereich#Lendengegend → r+l#Dentalgie#Zahnschmerzen#Gingiva*#Zahnfleisch#Gingivitis*#Regio hypogastrica#Schambereich, Schamgegend#Regio iliaca#Unterbauch → r+l#Regio inguinalis#Leistenregion#Leistengegend#Leiste → r+l#Regio glutealis#Gesäßregion#Gesäßgegend → r+l#Extremität(en)*#Gliedmaße(n)#obere Extremität:#Oberbauch betreffend#Regio hypochondriaca#Hypochondrium#Oberbauch unter den Rippenbögen → r+l#Mesogastrium#Mittelbauch#Regio umbilicalis#Axilla*#Achselhöhle#Brachium*#Oberarm#Antebrachium*#Unterarm#Cubitus*#Ellenbogen#Articulatio cubiti*#Ellenbogengelenk#Fossa cubitalis#Ellenbogengrube#Regio cubitalis anterior#Regio cubiti#anterior#Ellenbeuge#Fossa*#Grube#Skelett#Knochengerüst#Os(Ossa)*#Knochen#Mund#Manus*#Hand#Dorsum manus*#Handrücken#Palma manus#Volar#volaris#hohlhandwärts#in Bezug auf die Handfläche#handflächenwärts#Digitus(Digiti) manus*#Finger#Pollex#Digitus manus I*#Daumen#Index, Digitus manus II#Zeigefinger#Medius#Digitus manus III#Mittelfinger#Annularius#Digitus manus IV*#Ringfinger#Digitus minimus#Digitus manus V#kleiner Finger#Phalanx(Phalangen) (proximalis, media, distalis)*#Finger- oder Zehenglied(Finger- oder Zehenglieder)#(grundglied - mittelglied - endglied)#Unguis digitus manus #pedis#Fingernagel #Zehennagel#Unguis#Unguis incarnatus / subungual*#Nagel#eingewachsener Zehennagel#unter dem Nagel#Pelvis*#Becken#Mons pubis#Mons veneris#Schamberg#Schamhügel#Venushügel#Sura#Regio suralis#Wade#Wadenregion#Poplitea#Fossa poplitea#Kniekehle#Calcis*#Ferse#Hacke#Pes#Fuß(Füße)#Dorsum pedis#Fußrücken#Planta pedis#Planta*#Kinn#Pauke#Tuba auditiva#Tuba Eustachii#Ohrtrompete#eustachische Röhre#Bucca#Vola manus#Handfläche#Palmar#Palmaris#Regio buccalis*#Wange#Fußsohle#plantar#sohlenflächenwärts#im Bezug auf Fußsohle#Digitus(Digiti) pedis#Digitus malleus*"
let randomWords2 = "Zehe(n)#Hammerzehe#Hallux#Digitus pedis I*#Großzehe#Anatomie (Knochen)#Ostitis*#Knochenentzündung#Articulatio#Arthron#Arthr-#Das Gelenk#Membrana synovialis#Synovialis#Gelenkinnenhaut#Gelenkschleimhaut#Synovitis#Gelenkschleimhautentzündung#Gelenkinnenhautentzündung#Bursa synovialis*#Schleimbeutel#Gleitbeutel#Bursitis#Schleimbeutelentzündung#Vagina synovialis tendinis*#Sehnenscheide#artikulär, artikularis*#die Gelenke betreffend#zum Gelenk gehörend#Cranium*#Schädel#Calvaria#Schädeldach#Basis cranii#Schädelbasis#Cavum cranii#Schädelhöhle#Ossa cranii#Schädelknochen#Os frontale*#Stirnbein#Lobus*#Lappen (Sng.)#Lobus frontalis*#Stirnlappen#vordere Hirnlappen#Os parietale*#Scheitelbein#Os temporale*#Schläfenbein#Processus styloideus*#Griffelfortsatz (des Schläfenbeins)#Processus mastoideus*#Warzenfortsatz (des Schläfenbeins)#Os occipitale#Occiput*#Hinterhauptbein#Hinterkopf#Foramen magnum#großes Hinterhauptsloch des Schädels#Os sphenoidale*#Keilbein#Os ethmoidale*#Siebbein#Os lacrimale#Tränenbein#Os nasale*#Nasenbein#Cartilago nasi lateralis#Dreiecksknorpel#Cartilago septi nasi*#Septumknorpel#Os zygomaticum*#Jochbein#Arcus zygomaticus*#Jochbogen#Os hyoideum*#Zungenbein#Maxilla*#Oberkiefer#Mandibula*#Unterkiefer#Vertebra#vertebral*#Wirbel#die Wirbel betreffend#Foramen vertebrale#Foramen#Wirbelloch#Loch#Öffnung#Processus vertebra(e)#Wirbelfortsatz(ätze)#Corpus vertebra(e)#Corpus#Wirbelkörper#Körper#Processus spinosus*#Dornfortsatz#Processus transversus(rsi)#Querfortsatz(ätze)#Processus articularis(articulares)*#Gelenkfortsatz(ätze)#Processus costalis*#Rippenfortsatz#Columna vertebralis#Columna*#Wirbelsäule#Säule#Vertebrae cervicales (pl.) *#Halswirbel (pl.)#Atlas (Vertebra cervicalis I) *#Träger, Nicker#1. Halswirbel#Axis (Vertebra cervicalis II) *#Dreher#2. Halswirbel#Vertebra prominens (V. cervicalis VII) *#7. Halswirbel#Vertebrae thoracicae*#Brustwirbel (pl.)#Vertebrae lumbales*#Lendenwirbel (pl.)#Vertebrae sacrales#Os sacrum *#Kreuzbeinwirbel#Kreuzbein#Vertebrae coccygeae#Os coccygeum#Os coccygis*#Steißbeinwirbel#Steißbein#Kauda*#Schwanz#Endstück#Schultergürtel#Scapula*#Schulterblatt#Akromion#Schulterdach#Schulterhöhe#Processus coracoideus#Rabenschnabelfortsatz#Glenoid#Cavitas glenoidalis#Schultergelenkpfanne#Klavikula*#Schlüsselbein#Articulatio glenohumeralis#Articulatio#humeroscapularis#Schultergelenk#Omarthrose*#Schultergelenkverschleiß#Articulatio akromioklavikularis*#Schultereckgelenk, kleines Schultergelenk#obere Extremität:"
let randomWords3 = "Humerus#Humerusfraktur*#Oberarmknochen#Oberarmbruch#Caput humeri*#Oberarmknochenkopf#Olekranon*#Ellenbogenspitze#Ulna*#Elle#Radius*#Speiche#Articulatio manus#Handgelenk#Articulatio carpometacarpalis#Articulatio#carpometacarpalis I (pollicis)*#Handwurzel-Mittelhand-Gelenk#Daumensattelgelenk#Articulatio metacarpophalangealis#Articulatio metacarpophalangealis I (pollicis)#Fingergrundgelenk#Daumengrundgelenk#Handgelenkflexregion#Handgelenkbeugeseite#Carpus#Ossa carpi#Ossa carpalia*#Handwurzel#Handwurzelknochen#Os capitatum#Kopfbein#Os scaphoideum*#Kahnbein#Os hamatum#Hakenbein#Os lunatum*#Mondbein#Os pisiforme*#Erbsenbein#Os triquetrum#Dreieckbein#Os trapezium#großes Vieleckbein#Os trapezoideum#kleines Vieleckbein#Ossa metacarpi#Ossa metacarpalia*#Mittelhandknochen#Ossa digitorum manus#Fingerknochen#Pelvis#Os ilium*#Darmbein#Crista iliaca*#Darmbeinkamm#Os ischii#Tuber ischiadicum*#Sitzbein#Sitzbeinhöcker#Os pubis*#Schambein#radikulär#eine Nervenwurzel betreffend#Commotio#Contusio#Articulatio sacroiliaca, iliosacralis#Kreuzbein-Darmbein-Gelenk#Kreuzdarmbeinfuge#Beckengürtel#Coxa*#Hüfte, Hüftregion#Articulatio coxae*#Hüftgelenk#Acetabulum*#Hüftgelenkspfanne#Coxitis*#Hüftgelenkentzündung#Coxarthrose*#Hüftgelenkverschleiß#Untere Extremität:#Femur#Os femoris*#Oberschenkel#Oberschenkelknochen#Caput femoris*#Oberschenkelkopf#Hüftkopf#Collum femoris*#Oberschenkelhals#Corpus femoris#Oberschenkelkörper#Oberschenkelschaft#Trochlea*#Rolle#Rollknorpel#Walze#Flaschenzug#Trochanter major#minor *#großer#kleiner Rollhügel#Femurfraktur#Oberschenkelbruch#Genu#Knie#Articulatio genus#Kniegelenk#Patella#Kniescheibe#Meniscus *#scheibenförmiger Kniegelenkknorpel#Meniscus lateralis*#Außenmeniskus#Meniscus medialis*#Innenmeniskus#Meniskopathie#Erkrankung des scheibenförmigen Kniegelenkknorpels#Meniskektomie#Entfernung des scheibenförmigen Kniegelenkknorpels#Gonarthrose*#Kniegelenkverschleiß#Crus*#Unterschenkel#Schenkel#Bein#Tibia*#Schienbein#Caput tibiae#Plateau tibialis*#Schienbeinkopf#Fibula*#Wadenbein#Malleolus lateralis*#Außenknöchel#Malleolus medialis*#Innenknöchel#Articulatio talocruralis#oberes Sprunggelenk#Articulatio talotarsalis#unteres Sprunggelenk#Tarsus#Ossa tarsi#Ossa tarsalia*#Sprungbein#Calcaneus*#Caput, Cephalon#Kopf#Regio frontalis#Frons*#Stirnregion#Stirn#Regio temporalis#Fersenbein#Os naviculare**#Kahnbein#Os cuneiforme*#Keilbein#Os cuboideum#Würfelbein#Ossa metatarsi#Ossa metatarsalia#Mittelfußknochen#Ossa digitorum pedis"
let randomWords4 = "Zehenknochen#Kahnbein#Os scaphoideum (Knochen der Handwurzel)#Os naviculare (Knochen der Fußwurzel)#Keilbein#Os sphenoidale (Knochen des Schädels)#Os cuneiforme (Knochen der Fußwurzel)#Kondylus, Kondyle*#Gelenkkopf#Knochengelenk#Gelenkknöchel#Epikondylus, Epikondyle*#Gelenkhöcker#Diaphyse#Knochenschaft eines Röhrenknochens#Epiphyse#Gelenkende eines Röhrenknochens ① Zirbeldrüse ②#Metaphyse#Wachstumzone eines Röhrenknochens#Medulla ossium#Knochenmark#Cartilago, Chondros*#Der Knorpel#Cartilago articularis#Gelenkknorpel#Cartilago auricularis#Ohrknorpel#Cartilago costalis#Rippenknorpel#Chondritis*#Knorpelentzündung#Ossifikation*#Verknöcherung#Musculus(Musculi)#Muskel(n)#Musculus masseter#Kaumuskel#Musculus sternocleidomastoideus#Kopfnicker#Kopfwendermuskel#Musculus pectoralis major#minor*#großer#kleiner Brustmuskel#Bauchmuskulatur#Musculus rectus abdominis*#gerader Bauchmuskel#Musculus transversus abdominis#querer Bauchmuskel#Musculus obliquus externus#internus#abdominis#äußerer#innerer schräger Bauchmuskel#Musculus gluteus maximus#minimus*#großer#kleiner Gesäßmuskel#Musculus quadriceps femoris*#vierköpfiger Oberschenkelmuskel#Musculus tibialis anterior#vorderer Schienbeinmuskel#Ligamentum(Ligamenta)#Band(Bänder)#Ligamentum cruciatum anterius#posterius*#vorderes#hinteres Kreuzband#Ligamentum patellae*#Kniescheibenband#Kniescheibensehne#Ligamentum inguinale*#Leistenband#Canalis inguinalis*#Leistenkanal#Canalis femoralis#Schenkelkanal#Canalis vertebralis*#Wirbelkanal#Rückenmarkskanal#Thenar*#Daumenballen#Hypothenar#Kleinfingerballen#Rigidität#Rigor#rigide*#Steifigkeit#Starrheit#Starre#Steif#starr#magnus#major#maximus*#groß#parvus#minor#minimus*#klein#longus#brevis*#lang#kurz#Origo#Insertio *#Ursprung#Muskelursprung#Ansatz#Muskelansatz#-inkontinenz#ungewollter Abgang von → Harninkonti#nenz#-ographie#bildliche Darstellung#Umbilicus#Omphalos*#Nabel#Funiculus umbilicalis#Funiculus*#Nabelschnur#dünnes Seil#Strang#Funiculus spermaticus*#Mukosa*#Schleimhaut#Traumatologie#Traumatologe*#Unfallmedizin#Unfallheilkunde#Verletzungskunde#Wundenkunde#Unfallmediziner#Trauma#Verletzung#Polytrauma*#Mehrfachverletzung#polytraumatisiert*#mehrfachverletzt#Vulnerabilität#vulnerabel*#Anfälligkeit#Verletzlich#verwundbar#Arthropathie#Gelenkerkrankung#Arthralgie*#Gelenkschmerzen#Arthritis urica#Urikopathie*#Gicht#Arthrose#Osteoarthrose*#Gelenkverschleiß#degenerative Gelenkerkrankung#Ankylose*#Gelenkversteifung"
let randomWords5 = "Vs. Arthrodese#operative Gelenkversteifung#degenerativ#Degeneration#s. zurückbildend#s. abbauend#Verschleiß#Arthritis#Gelenkentzündung#Pseudarthrose*#Falschgelenk#Arthroskopie*#Gelenkspiegelung#Arthrektomie#Gelenkentfernung#Arthrotomie#Gelenkeröffnung#Arthrozentese#Gelenkpunktion#Punktion#Einstechen mit Hohlnadel#Synovia#Gelenkflüssigkeit#Gelenkschmiere#Hydarthros#Hydrops articularis#Gelenkerguss#Hämarthros#blutiger Gelenkerguss#Discus intervertebralis*#Bandscheibe#Zwischenwirbelscheibe#Discus#Scheibe#Nucleus pulposus#Gallertkern#Anulus fibrosus#Faserring#Bandscheibenentzündung#Diskektomie#Bandscheibenentfernung#intranasal#intraocular#durch die Nase#das Auge#per os#oral#Lumbago#Lumbalgie*#Hexenschuss#Wirbelsäulenkrümmung#Kyphose*#Wirbelsäulenkrümmung nach hinten#Lordose*#Wirbelsäulenkrümmung nach vorne#Skoliose*#seitliche Wirbelsäulenkrümmung#Genu valgum*#X-Bein#Genu varum*#O-Bein#Hallux valgus#Großzehenabweichung nach außen#Hallux varus#Großzehenabweichung nach innen#Pes valgus#Knickfuß#Pes equinus#Spitzfuß#Pes equinovarus*#Klumpfuß#Pes planus*#Plattfuß#Pes excavatus#Pes cavus#Hohlfuß#Pes calcaneus#Hackenfuß#Myalgie*#Muskelschmerzen#Myositis*#Muskelentzündung#Vs. Myelitis*#Rückenmarksentzündung#Myopathie#Muskelerkrankung#Amyotrophie, Muskelatrophie*#Muskelschwund#Muskeldystrophie*#Muskelschwäche#Muskelschwund#Myasthenie#Myasthenia gravis*#Muskelschwäche#autoimmune Muskelschwäche#Torticollis*#Schiefhals#Myom#gutartige Muskelgeschwulst#Tendo#Sehne#Tendinitis#Sehnenentzündung#Tendovaginitis, Tendosynovitis*#Sehnenscheidenentzündung#Tendo Achillis, Tendo calcaneus#Achillessehne#Tenotomie#operative Durchtrennung einer Sehne#Osteomyelitis*#Knochenmarkentzündung#Periost*#Knochenhaut#Periostitis*#Knochenhautentzündung#Osteogenese#Knochenneubildung#Osteolyse#Knochenabbau#Osteoporose*#Knochenschwund#Osteomalazie#Knochenerweichung#Osteom#Osteosarkom*#Gutartige#bösartige Knochengeschwulst#Osteogenesis imperfecta#Glasknochenkrankheit#Ruptur#Zerreißung#Riss#Fraktur*#Knochenbruch#frakturieren#brechen#frakturiert*#gebrochen#Fragilität#Anfälligkeit für Frakturen#fragil#leicht zerbrechlich#Frakturfragment#Fragment*#Bruchstück#Stück#Dislokation*#Verlagerung#Fehlstellung#Versetzung#Umsetzung#Luxation*#vollständige Verrenkung#Ausrenkung#Auskugelung#Subluxation#unvollständige Verrenkung#Luxationsfraktur#Verrenkungsbruch#Kontraktur#Verkürzung#Schrumpfung#Kontraktion#Kontrahieren#Kontraktieren#Kontrahieren#Adstringieren#kontraktil#adstringierend"
let randomWords6 = "Verkürzung#Zusammenziehung#Verkürzen#Zusammenziehen#zusammenziehend#Konstriktion#Striktur*#Verengung#Einengung#Einschnürung#Fissur#Fissura#Spalte#Riss#Einriss#Ritz#Rinne#Furche#Kluft#Schlitz#Neurologie#Systema nervosum centrale#zentrales Nervensystem#Encephalon#Gehirn#Cerebrum*#Großhirn#Cerebellum*#Kleinhirn#Diencephalon*#Zwischenhirn#Truncus cerebri#Truncus encephali*#Hirnstamm#Medulla oblongata#Bulbus cerebri#verlängertes Rückenmark#Bulbärhirn#Pons*#Brücke#Mesencephalon#Midbrain*#Mittelhirn#Cortex cerebri#Cortex*#Großhirnrinde#Rinde#Enzephalitis*#Gehirnentzündung#Enzephalopathie#Gehirnkrankheit#Cephalgie*#Kopfschmerzen#Rückenmark#Gyrus cerebri*#Gehirnwindung#Meningen*#Hirn- und Rückenmarkshäute#Dura mater*#harte Hirnhaut#Arachnoidea mater#Spinngewebshaut#Spinnwebenhaut#Pia mater*#Weiche#innere Hirnhaut#Meningitis*#Hirnhautentzündung#Liquor cerebri #Liquor cerebrospinalis*#Gehirnwasser#Gehirn- und Rückenmarksflüssigkeit#Hydrozephalus*#Wasserkopf#Opisthotonus#Nackensteifigkeit#Tentorium*#Zelt#Neuron#Nervenzelle#Systema nervosum periphericum#peripheres Nervensystem#Ganglion*#Nervenknoten#Überbein#Plexus*#Geflecht#Nervus(Nervi)#Nerv(en)#Nervi craniales#Hirnnerven#Nervus olfactorius 1*#Riechnerv#Nervus opticus 2*#Sehnerv#Chiasma opticum#Sehnervenkreuzung#Nervus facialis 7*#Gesichtsnerv#Nervus vestibulocochlearis 8#Hörnerv#Nervus vagus#10. Hirnnerv#Nervus spinalis#Spinalnerv#superficialis#superfiziell*#oberflächlich gelegen#zur Oberfläche#Nervus phrenicus#diaphragmaticus*#Zwerchfellnerv#Nervus splanchnicus major#großer Eingeweidenerv#Nervus splanchnicus minor#kleiner Eingeweidenerv#Neuritis*#Nervenentzündung#Innervation#Nervenversorgung#Neuralgie#Nervenschmerzen#Radix*#Wurzel#Radikulitis#Wurzelneuritis#Condylomata acuminata*#Feigwarzen#Genitalwarze#Dermatologin*#Compressio cerebri*#Gehirn- erschütterung#Prellung#quetschung#Apoplex#Apoplexie#apoplektischer Insult#Schlaganfall#Epilepsie*#Krampfanfall#Fallsucht#Krampfleiden#Parkinson*#Schüttellähmung#Spina bifida*#Wirbelspalt#offene Wirbelsäule#Meningozele#Hirnhautbruch#Vorwölbung von Dura mater durch den#Wirbelspalt#Meningomyelozele#Vorwölbung von Dura mater und Rückenmark durch den Wirbelspalt#Symptom#Krankheitszeichen#Beschwerden#Prodrom*#Vorzeichen#Frühsymptom#Vigilanz*#Wachheit#Wachsamkeit#Benommenheit#reduzierte Wachheit#Somnolenz#somnolent*#abnorme Schläfrigkeit#schläfrig#Sopor#tiefe Schläfrigkeit#Koma#tiefer Schlaf#nicht weckbar"
let randomWords7 = "tiefe Bewusstlosigkeit#Lethargie#Schläfrigkeit#Narkolepsie#Schlafkrankheit#Konfusion*#Verwirrung#Coma vigile#Wachkoma#Delirium#delirant*#Bewusstseinsstörung#Bewusstseinstrübung#verwirrt#Halluzination#Illusion#Sinnestäuschung#Wahnwahrnehmungsstörung#Trugwahrnehmung#Agnosie*#Störung des Erkennens#Amnesie*#Gedächtnisverlust#Erinnerungslücke#Alzheimer#Demenz#Insomnie#Dyssomnie*#Einschlafstörung#Schlaflosigkeit#Schlafstörung#Parasomnie#Somnambulismus*#Durchschlafstörung#Schlafwandeln#Demenz#geistiger Verfall#Dysarthrie#Sprechstörung#Anarthrie#Sprechverlust#Dysphasie#Sprachstörung#Aphasie#Sprachverlust#Dysphonie*#Stimmstörung#Heiserkeit#Aphonie#Stimmlosigkeit#Dyslalie*#Stammeln#Artikulationsstörung#Tic#Muskelzuckungen#Dyslexie#Legasthenie#Lesestörung#Alexie#Leseblindheit#Logopädie#Sprachheilkunde#Sprachtherapie#Restless-Legs-Syndrom#unruhige Beine#Enzephalomyelitis#Gehirn- und Rückenmarksentzündung#Enzephalomyelitis disseminata (ED)#Multiple Sklerose (MS)#Ataxie#Dysdiadochokinese*#Bewegungskoordinationsstörung#Sensus#Sinn#Gefühl#Sensation#Empfindung#Wahrnehmung#Verminderung#Steigerung der sensiblen Wahrnehmung#Anästhesie*#Betäubung#kompletter Ausfall#Hypästhesie#Taubheitsgefühl#Hyperästhesie#Überempfindlichkeit#qualitative Veränderungen (Missempfindungen)#Parästhesie*#Kribbeln#schmerzlose Missempfindung#Dysästhesie#Schmerzhafte#unangenehme Missempfindung#Motus#Bewegung#Parese (-parese) *#Unvollständige#teilweise Lähmung → Erschlaffung#Fazialisparese*#Gesichtslähmung#Paraparese#teilweise Lähmung beider Beine#Hemiparese#teilweise Halbseitenlähmung#Lähmung einer Körperseite#Tetraparese#teilweise Lähmung aller vier Extremitäten#Paralyse (-plegie)#vollständige Lähmung → Schwächung#Paraplegie#vollständige Lähmung beider Beine#Hemiplegie*#vollständige Halbseitenlähmung#Lähmung einer Körperseite#Tetraplegie#vollständige Lähmung aller vier Extremitäten#Neurologe#Nervenarzt#Ophthalmologie & Augen#Orbita*#Augenhöhle#Oculus, Ophthalmos*#Auge#Kornea*#Hornhaut des Auges#Keratitis*#Hornhautentzündung#Limbus corneae#Cornealrand#Limbus, Saum#Margo anterior#Rand#Vorderrand#Konjunktiva*#Bindehaut des Auges#Konjunktivitis*#Bindehautentzündung#Iris*#Regenbogenhaut des Auges#Samenstrang#Omphalitis*#Nabelentzündung#Isthmus*#Enge#Frenulum*#Bändchen#kleine Schleimhautfalte#Bauchspeicheldrüse#Pankreatitis*#Bauchspeicheldrüsenentzündung#Diabetes mellitus#Zuckerkrankheit#Gigantismus#Riesenwuchs#Augenlinse#Linse#Aphakie*#Fehlen der Augenlinse#Dysphakie*"
let randomWords8 = "Fehllage der Augenlinse#Bulbus oculi*#Augapfel#Ablatio retinae*#Netzhautablösung#Pupille#Sehloch#Mydriasis*#Pupillenerweiterung#Miosis*#Pupillenverengung#Isokorie#Seitengleichheit der Pupillen#Anisokorie#Seitenungleichheit#Seitendifferenz der Pupillen#Uvea#Tunica media bulbi  besteht aus drei Anteilen:#Gefäßhaut#mittlere Augenhaut#1. Corpus ciliare#Ziliarkörper#2. Iris#3. Choroidea#Uveitis#Gefäßhautentzündung#Cilium, Zilie(n)#Wimper(n)#Corpus vitreum#Glaskörper#Camera anterior bulbi#Augenvorderkammer#Apparatus lacrimalis#Tränenapparat#Glandula lacrimalis*#Tränendrüse#Canalis lacrimalis#Tränenkanal#Saccus lacrimalis*#Tränensack#Ductus nasolacrimalis*#Tränennasengang#Lacrimal drainage#Tränenfluss#Palpebra#Blepharon#Augenlid#Ptosis#Ptose#Lidsenkung#Hordeolum*#Gerstenkorn#Chalazion#Hagelkorn#Blepharitis#Augenlidentzündung#Visus*#Sehschärfe, Sehstärke#Emmetropie#Normalsichtigkeit#Ametropie; 3 Formen:#Fehlsichtigkeit#Hyperopie, Hypermetropie#Weitsichtigkeit, Übersichtigkeit#Myopie#myop#Kurzsichtigkeit#kurzsichtig#Astigmatismus#Stabsichtigkeit#Presbyopie#Altersweitsichtigkeit#Amblyopie*#Schwachsichtigkeit#Diplopie#Doppel(t)sehen#Nyktalopie#Nachtblindheit#Hemeralopie#Tagblindheit#Hemianopsie*#Halbseitenblindheit#Amaurose#Amaurosis*#vollständige Blindheit#Amaurosis fugax*#vorübergehende Blindheit#Skotom*#Gesichtsfeldausfall#Strabismus*#Schielen#Nystagmus*#Augenzittern#intraokulärer Druck#Augeninnendruck#Glaukom*#grüner Star#erhöhter Augeninnendruck#Katarakt*#grauer Star#Linsentrübung#Enophthalmie#Enophthalmus#Zurücktreten des Augapfels#Exophthalmie#Exophthalmus#Protrusio bulbi#Hervortreten des Augapfels#Funduskopie#Augenspiegelung#Ophthalmologie*#Augenheilkunde#Ophthalmologe#Ophthalmologin *#Augenarzt #Augenärztin#Kardiologie#Angiologie#Herzkreislaufsystem#Cor#Herz#Atrium*#Herzvorhof#Ventriculus cordis#Ventrikel cordis dexter#sinister *#rechter#linker Herzkammer#Septum cordis*#Herzscheidewand#Septum interatriale cordis#Vorhofscheidewand#Septum interventriculare#cordis#Kammerscheidewand#Atriumseptumdefekt (ASD)#Loch in der Vorhofscheidewand#Ventrikelseptumdefekt (VSD)#Loch in der Herzkammerscheidewand#Foramen ovale#ovales Loch in der Vorhofscheidewand#Valva(Valvae) cordis#Valva*#Herzklappe(n)#Klappe#Valva aortae#Aortenklappe#Valva trunci pulmonalis#Pulmonalklappe#Valva mitralis#Mitralklappe#Valva tricuspidalis#Trikuspidalklappe#Endokard#Herzinnenhaut#Endokarditis*#Herzinnenhautentzündung#Myokard#Herzmuskel"
let randomWords9 = "Myokarditis#Herzmuskelentzündung#Myokardinfarkt*#Herzinfarkt#Myokardinsuffizienz#Herzinsuffizienz#Herzmuskelschwäche#Herzschwäche,#Herzleistungsschwäche#Kardiomyopathie#Herzmuskelerkrankung#Kardiomegalie#krankhafte Herzmuskelvergrößerung#kardiotoxisch#herzschädigend#Perikard*#Herzbeutel#Perikarditis*#Herzbeutelentzündung#Perikarderguss#Flüssigkeitsansammlung im Herzbeutel#Apex cordis#Herzspitze#Herzrhythmus#Herzfrequenz#Schlagfrequenz#Systole#Zusammenziehungsphase des Herzmuskels#Diastole#Erschlaffungsphase des Herzmuskels#Tachykardie*#Herzrasen#Herzjagen#beschleunigte Herzfrequenz#Bradykardie#verlangsamte Herzfrequenz#Arrhythmie#Herzrhythmusstörung#Palpitation*#Herzklopfen#Herzpochen#Extrasystole*#Extraschlag#Herzstolpern#Asystolie#Herzstillstand#Vas#vaskulär *#Gefäß#in Bezug auf Blutgefäße#Angiitis#Vaskulitis*#Blutgefäßentzündung#Mikroangiopathie#Makroangiopathie#Erkrankung der kleinen#großen Blutgefäße#1. Arterie#Schlagader#Aorta*#Hauptschlagader#Arcus aortae#Arcus*#Hauptschlagaderbogen#Bogen#Arteria cerebri*#Hirnschlagader#Arteria carotis*#Halsschlagader#Arteria coronaria#Herzkranzschlagader#Herzkranzarterie#Arteria femoralis*#Oberschenkelschlagader#Arteria poplitea#Kniekehlenschlagader#Arteriitis#Schlagaderentzündung#Arteriosklerose#Atherosklerose*#Arterienverkalkung#Gefäßverkalkung#Carotissklerose*#Halsschlagaderverkalkung#verhärtung#Koronarsklerose*#Herzkranzschlagaderverkalkung#Carotisstenose*#Halsschlagaderverengung#Aortenstenose#Hauptschlagaderverengung#Sklerose#Stenose#Bougierung#Verhärtung#Verkalkung#Verengung#Einengung#Aufdehnung#2. Vene#Blutader#Phlebitis*#Venenentzündung#Phlebektomie*#Venenentfernung#Phlebotomie#Aderlass#Vena jugularis externa*#äußere Drosselvene#Vena poplitea#Kniekehlenvene#Vena portae#Pfortader#Vena cava superior#inferior*#obere#untere Hohlvene#3. Kapillare(n)#Haargefäß(e)#Systema lymphaticum#lymphatisches System#Vas lymphaticum#Lymphgefäß#Nodus lymphaticus(Nodi lymphatici)#Nodus,Nodulus(Nodi)#Lymphknoten (Pl.=Sng.) #Knoten#Lymphadenitis#Lymphangiitis*#Lymphknotenentzündung #Lymphgefäßentzündung#Lymphadenopathie#Lymphknotenerkrankung#Lymphe#Gewebeflüssigkeit#Zwischenzellflüssigkeit#Lymphödem#Schwellung durch Lymphstauung#Symphysis pubica#Symphyse*#Schambeinfuge#Beinödem#Wassereinlagerung im Bein#Ischämie*#Minderdurchblutung#Mangeldurchblutung#Claudicatio*#Hinken#Claudicatio intermittens*#Schaufensterkrankheit (pAVK: periphere arterielle #erschlusskrankheit)#Aneurysma"
let randomWords10 = "örtliche Wanderweiterung des Herzens#einer Schlagader#Angiospasmus#Vasospasmus*#Gefäßkrampf#Spasmus#Krampf#Verkrampfung#Thrombus*#Blutgerinnsel#Thrombose#Verstopfung eines Blutgefäßes durch ein Blutgerinnsel#Thrombophlebitis#oberflächliche Beinvenenentzündung#Phlebothrombose (TVT)#tiefe Beinvenenentzündung#Embolus#Gefäßpfropf#Embolie#Embolismus#Verschluss eines Blutgefäßes durch einen Gefäßpfropf#Arterielle#pulmonale Hypertonie#Bluthochdruck#Lungenhochdruck#Hypotonie#niedriger Blutdruck#Schock#vaskulär  Kreislaufversagen#Kreislaufstillstand psychisch  seelische Erschütterung#Synkope*#Ohnmacht#Kreislaufkollaps#kurze Bewusstlosigkeit#Kollaps#Zusammenbruch#Angina pectoris*#Brustenge#Contusio#Kontusion#Prellung#Contusio cordis#Herzprellung#Pulsus paradoxus#Pulsschwächung während Einatmung#Atrium fibrillation#Vorhofflimmern#Cor pulmonale#Rechtsherzbelastung aufgrund Lungenhochdruck#Vitium#Vitium cordis#Herzklappenvitium*#Fehler\#Herzfehler#Herzklappenfehler#Echokardiographie#Ultraschalluntersuchung des Herzens#Angiographie#Bildliche#radiologische Gefäßdarstellung#Kanüle#Venenverweilkanüle#Braunüle*#Hohlnadel#Viggo#Zugang#Injektion#injizieren*#Einspritzung#einspritzen#Infusion#Tropf#Flüssigkeitsgabe in die Venen#intravenös#in die#der Vene#Pacemaker*#Herzschrittmacher#Sudor#Schweiß#Anhidrose#Hypohidrose#Schweißausbruch#Kardiologe#Kardiologie *#Facharzt für Herzkrankheiten#Lehre von Herzkrankheiten#Angiologe#Angiologie#Gefäßarzt#Gefäßheilkunde#Fachgebiet für Gefäßerkrankungen#Bypass#künstlich angelegte Umgehung eines Blutgefäßabschnittes#Ligatur#Unterbindung#Reanimation (CPR)#Herz-Lungen-Wiederbelebung#Hämatologie & Blut #Blutzelle(n)*#Blutkörperchen#Erythrozyt(en) *#rotes Blutkörperchen#Leukozyt(en) *#weißes Blutkörperchen#Leukozytose*#Vermehrung der weißen Blutkörperchen#Leukopenie, Leukozytopenie#Verminderung der weißen Blutkörperchen#Makrophage#Phagozyt#Monozyt#Fresszelle#Thrombozyt(en) *#Blutplättchen#Thrombozytose#Vermehrung der Blutplättchen#Thrombopenie#Thrombozytopenie*#Verminderung der Blutplättchen#Polyzythämie#Vermehrung der roten Blutkörperchen#Panzytopenie#Verminderung aller Blutkörperchen#Hämatopoese*#Blutbildung#Hämolyse#Auflösung von roten Blutkörperchen#Hämoglobin*#roter Blutfarbstoff#Anämie*#Blutarmut#Leukämie#Blutkrebs#Hämorrhagie*#Blutung#Blutverlust#Hämostase#Blutstillung#Blutgerinnung#Hypovolämie*#Volumenmangel#vermindertes Blutvolumen#Hämopathie*#Bluterkrankung#Hämophilie#hämorrhagische Diathese*"
let randomWords11 = "Bluterkrankheit#Blutgerinnungsstörung#Blutungsneigung#Hämodialyse#Dialyse#Blutwäsche#Hyperlipidämie*#erhöhte Blutfettwerte#Regio occipitalis#Hinterhauptsregion#Regio parietalis#Scheitelregion#Facies*#Gesicht#Regio mentalis#Mentum*#Kinnregion#Wangenregion#Regio nasalis#Nasenregion#Regio oralis#Mundregion#Nucha*#Nacken#Collum#Cervix#Hals#Soma#somatisch#Körper#körperlich#Hyperglykämie#erhöhter Blutzuckerspiegel#Hypoglykämie*#nedriger Blutzuckerspiegel#agglutinieren*#Verklumpung#Zusammenballung#verklumpen#Koagulation#Koagulieren#koaguliert*#Gerinnung#Gerinnen#geronnen#Sepsis*#Blutvergiftung#Plasmapherese#Plasmaaustauschbehandlung#Pulmologie & Atmungssystem#Cavum nasi#Nasenhöhle#Concha(e) nasalis superior#Media#inferior*#obere#mittlere#untere Nasenmuschel(n)#Pharynx*#Rachen#Pharyngitis*#Rachenentzündung#Rhonchopathie#Schnarchen#Larynx#Larynxödem *#Kehlkopf#Kehlkopfschwellung#Prominentia laryngea#Adamsapfel#Laryngitis*#Kehlkopfentzündung#Krupp#lebensbedrohliche Kehlkopfentzündung#Epiglottis*#Kehldeckel#Epiglottitis*#Kehldeckelentzündung#Cartilago cricoidea#Ringknorpel#Cartilago thyroidea#Schildknorpel#Ligamentum vocale*#Stimmband#Plica vocalis#Unterzuckerung#Protein#Eiweiß#Albumin#Bluteiweiß#Agglutination#Labia vocalis*#StimmfalteStimmlippe#Plica*#Falte#Wulst#Laryngoskopie*#Kehlkopfspiegelung#Laryngektomie#Kehlkopfentfernung#Kehlkopfamputation#Larynxkarzinom#Kehlkopfkrebs#Trachea*#Luftröhre#Tracheitis*#Luftröhrenäste betreffend#Bronchiektasie#Atemwegserweiterung#Bronchitis#Atemwegsentzündung#Bronchialkarzinom*#bösartige Geschwulst der Luftröhrenäste#Bronchospasmus#Bronchoskopie*#Spiegelung der Luftröhrenäste#Intrakraniell#intrakranial#innerhalb des Schädels#Medulla spinalis#Myelon*#Pulmo#Pneumon#pulmonal*#Lunge#in Bezug auf die Lunge#Pulmo dexter#sinister#rechter#linker Lungenflügel (Lunge)#Lobi pulmonis#Lungenlappen#Lobektomie#Lungenlappenentfernung#Pneumonie*#Lungenentzündung#Lobärpneumonie#Lungenlappenentzündung#Fissura obliqua#horizontalis pulmonis#schräge#quere Furche der Lunge#obliqua, obliquus*#schräg#Alveolus#Alveole(Alveolen)#Lungenbläschen#Pleura#Brustfell#Pleura parietalis#costalis*#Rippenfell#Pleura visceralis#pulmonalis*#Lungenfell#Cavum pleurae#Cavitas#pleuralis#Brustfellhöhle#Pleurahöhle#Pleuraspalt#Pleuritis#Brustfellentzündung#Pleurolyse#operative Ablösung von Verwachsungen der Pleura#Pleurodese#Verklebung des Pleuraspalts#Pleurodynie#Brustfellschmerzen#Diaphragma*#Zwerchfell#Mediastinum #Cavum mediastinale"
let randomWords12 = "Mittelfell#Mittelfellraum#Respiration#Spiro, -pnoe#Atmung#Dyspnoe*#Atemnot#Atemstörung#Luftnot#Orthopnoe#Atemnot im Liegen#Apnoe*#Atemstillstand#Diskusprolaps*#Bandscheibenvorfall#Diszitis#Schlafapnoe#Atemstillstände während des Schlafs#Bradypnoe#verlangsamte Atemfrequenz#Tachypnoe#Schnellatmung#beschleunigte Atemfrequenz#Eu-#Hyper-#vertiefte Atmung#Respirator#Beatmungsgerät#Inspiration*#Einatmung#Exspiration*#Ausatmung#Ventilation#Hypoventilation#Hyperventilation*#Lüftung, Belüftung#Verlangsamte#beschleunigte Lüftung#Adult Respiratory Distress Syndrom (ARDS)#akutes Lungenversagen#Schocklunge#chronisch obstruktive Lungenerkrankung (COPD#chronische Verengung der Atemwege#Raucherhusten#Emphysem#Lungenaufblähung#Asthma bronchiale#anfallsartige Atemnot#Stridor*#Pfeifendes#zischendes Atemgeräusch#Atemnebengeräusch#Pneumokoniose#Staublunge#Silikose*#Quarzstaublunge#Hypo- pnoe#Normale#Flache#Lungenfibrose#krankhafter Umbau von Lungengewebe in Bindegewebe#Atelektase#Lungenkollaps#Zusammenfall eines Lungenteils#Lungenödem#Wasserlunge#Flüssigkeitsansammlung in der Lunge#Aspiration#Fremdstoffeinatmung#Verschlucken#Ansaugen#Zyanose#Cyanosis#Blausucht#Blauverfärbung der Haut#Tuberkulose#Morbus Koch#Schwindsucht#Influenza*#Grippe#Sternutatio#Niesen#Tussis*#Husten#Expektoration#expektorieren*#Abhusten#abhusten#Expektorat#Sputum*#Auswurf#purulent#eitrig#mucopurulent#schleimig & eitrig#Hämoptyse, Hämoptoe#Bluthusten#Pleuraerguss#Flüssigkeitsansammlung im Pleuraspalt#Pneumothorax#krankhafte Luftansammlung im Pleuraspalt#operative Eröffnung der Luftröhre#Bronchus#Bronchie(Bronchien)*#Luftröhrenast(äste)#Hämatopneumothorax#krankhafte Blut– und Luftansammlung im Pleuraspalt#Pulmologie#Pneumologie#Lungenheilkunde#Lehre von Lungenerkrankungen#Pulmologe#Facharzt für Lungenerkrankungen#Gynäkologie#weibliches Genitalsystem#Ovar#Ovarium#Oophoron#Eierstock#Oophoritis, Ovaritis*#Eierstockentzündung#Ovariektomie, Oophorektomie*#Eierstockentfernung#Ovum#O(v)ozyt*#Ei#Eizelle#Ovarialzyste#Eierstockzyste#Penetration#Durchdringung#Eindringen#Salpinx#Tuba uterina#Tuba#Tubus*#Eileiter#Röhre#Salpingitis*#Eileiterentzündung#Salpingektomie#Eileiterentfernung#Adnexe#Eierstöcke und Eileiter#Adnexitis#Entzündung der Eierstöcke und Eileiter#Adnektomie*#Entfernung der Eierstöcke und Eileiter#Uterus#Hystera#Metra#intrauterin*#Gebärmutter#innerhalb der Gebärmutter#Cavum uteri#Cavum#Gebärmutterhöhle#Hohlraum#Ostium uteri externum#internum,"
let randomWords13 = "Portio vaginalis uteri#Äußerer#innerer Gebärmuttermund#Cervix uteri*#Gebärmutterhals#Zervixkarzinom*#Gebärmutterhalskrebs#Endometrium#Endometritis#Gebärmutterschleimhaut#Gebärmutterschleimhautentzündung#Myometrium#Gebärmuttermuskel#Uterusmyom#gutartige Muskelgeschwulst der Gebärmutter#Descensus uteri#Uterusprolaps*#Gebärmuttersenkung#Gebärmuttervorfall#Uteroskopie#Hysteroskopie *#Gebärmutterspiegelung#Hysterektomie#Gebärmutterentfernung#Vagina (Kolpos-)*#Scheide#Vaginitis, Kolpitis*#Scheidenentzündung#Fluor vaginalis, Fluor genitalis*#Scheidenausfluss#Vaginismus#Scheidenkrampf#Vaginalruptur#Scheidenriss#Kolporrhexis#Kolporrhaphie#Scheidenabriss#Scheidenvernähen#Kolposkopie#Scheidenspiegelung#Genital(Genitalien)#Geschlechtsorgan(e)#Vulva#äußere weibliche Geschlechtsorgane#Vulvitis*#Entzündung der äußeren weiblichen Geschlechtsorgane#Cheilos#Labium oris#Labium#pudendi(Labia, Labien)*#Lippe(n)#Schamlippe(n)#Labia majora pudendi*#große, äußere Schamlippen#Labia minora pudendi*#Kleine#innere Schamlippen#Klitoris#Kitzler#Introitus vaginae#Scheideneingang#Hymen*#Jungfernhäutchen#Jungfernhaut#Ovulation#Follikelsprung#Eisprung#Fertilisation*#Befruchtung#Zygote#befruchtete Eizelle#In-Vitro-Fertilisation#künstliche Befruchtung#fertil#Fertilität#Fruchtbar#Fruchtbarkeit#Steril#Infertil#Steril#aseptisch*#unfruchtbar#keimfrei#antiseptisch#Sterilisation#Keimbekämpfend#Entkeimung#Entfernung der Keimdrüsen#Sterilität#Infertilität#Unfruchtbarkeit#Corpus luteum*#Gelbkörper#Gravidität#Gestatio*#Schwangerschaft#Gravid#gravidus*#schwanger#Gravide#Gravida*#Schwangere#Tubargravidität#Extrauteringravidität#ektope Gravidität#Eileiterschwangerschaft#Schwangerschaft#außerhalb der Gebärmutterhöhle#Hyperemesis gravidarum#übermäßiges Schwangerschaftserbrechen#Plazenta*#Mutterkuchen#Placenta praevia#Fehllage des Mutterkuchens#Ablatio placentae#vorzeitige Ablösung des Mutterkuchens#Chorion*#Zottenhaut#Amnion*#Fruchtblase#Liquor amnii#Fruchtwasser#Amnioskopie#Fruchtwasserspiegelung#Amniozentese#Fruchtwasserpunktion#Fruchtwasserentnahme#Embryo#Keim#Keimling (ungeborenes Kind bis der 9.#Schwangerschaftswoche)#Fetus, Fötus#ungeborenes Kind ab der #9. Schwangerschaftswoche#Infant#Säugling#Kleinkind#Geminus(Gemini)*#Zwilling(e)#Partus#Geburt#Entbindung#Partus praematurus*#Frühgeburt#Frühgeburtlichkeit#Partus serotinus#Spätgeburt#Abort#Fehlgeburt#Interruptio*#Schwangerschaftsabbruch#Abtreibung#maturus#reif#Perineum#Damm#Episiotomie*#Dammschnitt"
let randomWords14 = "Präeklampsie#Schwangerschaftsvergiftung#Sectio caesarea*#Kaiserschnitt#Abrasio uteri*#Ausschabung#Auskratzung der Gebärmutterschleimhaut#Kürettage#Postpartal#post partum#nach der Geburt#Puerperium*#Wochenbett#Puerperalfieber*#Wochenbettfieber#Hermaphrodit*#Zwitter#Mamma#Glandula mammaria#weibliche Brust#Brustdrüse#Mastitis*#Brustdrüsenentzündung#Mamille(n)#Papilla mammae#Thelitis*#Brustwarze(n)#Brustwarzenentzündung#Laktation#Muttermilchproduktion#Galaktorrhoe#krankhafter Milchfluss#Gynäkomastie#krankhafte Vergrößerung der männlichen Brustdrüsen#Mastektomie#Ablatio mammae#Brustentfernung#Brustamputation#Mammakarzinom*#Brustkrebs#bösartige Geschwulst der Brust#Klimakterium#Klimax*#Wechseljahre der Frau#Menstruation#Menorrhoe#Menses*#Regelblutung#Monatsblutung, Periode#Menarche#erste Monatsblutung#Menopause#letzte Monatsblutung#Menorrhagie#verlängerte Monatsblutung#Brachymenorrhoe#verkürzte Monatsblutung#Hypermenorrhoe#starke Monatsblutung#Hypomenorrhoe#Oligomenorrhoe#schwache Monatsblutung#zu seltene Monatsblutung#Metrorrhagie#azyklische Monatsblutung#Zwischenblutung#Amenorrhoe#Ausbleiben der Monatsblutung#Hormonentzugblutung#Abbruchblutung#Dysmenorrhoe#schmerzhafte Monatsblutung#Libido#Geschlechtstrieb#Koitus*#Geschlechtsverkehr#Dyspareunie#schmerzhafter Geschlechtsverkehr#Lavage*#Spülung#Mammographie#Röntgenuntersuchung der weiblichen Brust#Gynäkologie#Frauenheilkunde#Fachgebiet für Frauenerkrankungen#Gynäkologin*#Frauenärztin#Fachärztin für Frauenerkrankungen#Otorhinolaryngologie & HNO#Nasus#Rhin-#Nase#Naris(Nares)#Nasenöffnung#Nasenloch#Naseneingang#Septum nasi*#Nasenscheidewand#Nasentrennwand#Rhinitis*#Schnupfen#Nasenschleimhautentzündung#allergische Rhinitis#Pollinose#Heuschnupfen#Rhinoplastik*#Nasenkorrektur#Rhinoskopie#Nasenspiegelung#Anosmie*#Riechsverlust#Hyposmie#Riechsminderung#Epistaxis#Rhinorrhagie#Nasenbluten#heftiges Nasenbluten#Rhinorrhoe#laufende Nase#Nasenlaufen#Sinus paranasales#Sinus *#Nasennebenhöhlen#Höhle#Sinus frontalis*#Stirnhöhle#Sinus maxillaris*#Oberkieferhöhle#Kieferhöhle#Sinus sphenoidalis#Keilbeinhöhle#Sinus ethmoidales#Cellulae#ethmoidales#Siebbeinhöhlen#Siebbeinzellen#Sinusitis#Sinusitis maxillaris *#Nasennebenhöhlenentzündung#Kieferhöhlenentzündung#Sella turcica#Sella*#Türkensattel#Sattel#Auris#Ous*#Ohr#Otitis*#Ohrenentzündung#Auris externa*#Außenohr#Auricula auris#Ohrmuschel#Meatus acusticus externus*#äußerer Gehörgang#Zerumen, Cerumen*#Ohrenschmalz"
let randomWords15 = "Otomykose#Pilzinfektion des äußeren Gehörganges#Membrana tympani*#Trommelfell#Paukenfell#Myringitis*#Trommelfellentzündung#Parazentese#Myringotomie#Trommelfellschnitt#Trommelfelldurchstechung#Trommelfell perforation#Trommelfellloch#Trommelfellverletzung#Perforation#Durchbruch#Durchbohrung#Auris media*#Mittelohr#Cavitas tympanica, Tympanum*#Paukenhöhle#Ossicula auditiva#Gehörknöchelchen#Malleus*#Hammer#Incus*#Amboss#Stapes*#Steigbügel#Fenestra ovalis#Vestibuli#Fenestra*#ovales Fenster#Fenster#Fenestra rotunda#ochleae#rundes Fenster#Schneckenfenster#Otitis media#Mittelohrentzündung#Cholesteatom#Perlgeschwulst#Zwiebelgeschwulst#Auris interna#Labyrinth#Innenohr#Cochlea*#Hörschnecke#Scala#Treppe#Ductus semicircularis)es)#Bogengang(Bogengänge)#Vestibulum*#Vorhof des Innenohrs, Eingangsbereich#Vestibularapparat#Gleichgewichtsorgan#Meatus acusticus internus#innerer Gehörgang#Labyrinthitis*#Innenohrentzündung#Anakusis#Hörverlust#Gehörlosigkeit#Tinnitus#Ohrensausen#Ohrgeräusch#Vertigo*#Schwindel#Gleichgewichtsstörung#Presbyakusis*#Altersschwerhörigkeit#Otalgie#Otodynie*#Ohrenschmerzen#Otologe*#Ohrenarzt#Otologie*#Ohrenheilkunde#Fachgebiet für Ohrenkrankheiten#Palatum*#Gaumen#Palatum durum#harter Gaumen#Palatum molle #mollis#weicher Gaumen#weich#Velum palatinum#Velum*#Gaumensegel#Segel#Tonsille(n)#Mandel(n)#Tonsilla lingualis#Zungenmandel#Tonsilla palatina*#Gaumenmandel#Tonsilla pharyngea*#Rachenmandel#Tonsilla tubaria#Tubenmandel#Tonsillitis, Angina tonsillaris*#Mandelentzündung#Tonsillektomie#Tonsillotomie *#Gaumenmandelentfernung#teilweise Gaumenmandelentfernung#Adenotomie#Adenotonsillektomie*#Rachenmandelentfernung#Rachenmandel- und#Gaumenmandelentfernung#Oto–Rhino–Laryngologie (ORL)#Hals–Nasen–Ohren–Heilkunde (HNO)#Gastroenterologie#Verdauungssystem#Os#Oris#Stoma*#Mund#Cavitas oris#Mundhöhle#Stomatitis*#Mundschleimhautentzündung#Halitosis#Foetor ex ore#Mundgeruch#Labium oris#Cheilos#Lippe#Cheiloschisis#Lippenspalte#Hasenscharte#Cheilosis, Cheilitis#Lippenentzündung#Uvula#Uvula palatina*#Zäpfchen#Gaumenzäpfchen#Palatoschisis#Palatum fissum#Gaumenspalte#Cheilognathopalatoschisis#Lippen-Kiefer-Gaumenspalte#Dens*#Zahn#Dens serotinus#Weisheitszahn#Iritis*#Regenbogenhautentzündung#Retina*#Netzhaut des Auges#Retinitis#Retinopathie*#Netzhautentzündung#Karies*#Zahnfäule#Zahnfleischentzündung#Glossa#Lingua#Zunge#Lingual#sublingual*#die Zunge betreffend#unter der Zunge#Frenulum linguae*#Zungenbändchen#Lingua bifida#Glossoschisis"
let randomWords16 = "Zungenspalte#Spaltzunge#Makroglossie#Vergrößerung der Zunge#Mikroglossie#Verkleinerung der Zunge#Glossitis*#Zungenentzündung#Ösophagus#Ösophagitis*#Speiseröhre#Speiseröhrenentzündung#Ösophagoskopie*#Speiseröhrenspiegelung#Ructus#Ruktus#Ruktation#Regurgitation*#Aufstoßen#Rülpsen#Bäuerchen#Pyrosis*#Sodbrennen#Reflux*#Rückfluss#Gastroösophageale#Refluxkrankheit (GERD)#Speiseröhrenentzündung wegen Rückfluss der Magensäure#Gaster#Ventriculus*#Magen#Fundus#Magengewölbe#Kardia#Mageneingang#Corpus#Magenkörper#krampfartige Verengung der Luftröhrenäste#Bronchiallavage#Spülung der Luftröhrenäste#Pylorus*#Magenpförtner#Magenausgang#Curvatura gastrica major#minor#große#kleine Magenkurvatur#Peristaltik#Bewegung von Hohlorganen#Ulcus ventriculi*#Magengeschwür#Ulcus duodeni*#Zwölffingerdarmgeschwür#Gastritis*#Magenschleimhautentzündung#Gastroparese*#Magenlähmung#Magenatonie#Gastroskopie*#Magenspiegelung#Gastrektomie*#Magenentfernung#agastrisch#ohne Magen#Aerophagie*#Luftschlucken#Globusgefühl#Fremdkörpergefühl#Lien#Splen*#Milz#Milzruptur#Milzriss#Hämothorax#krankhafte Blutansammlung im Pleuraspalt#Pyothorax#krankhafte Eiteransammlung im Pleuraspalt#Splenomegalie*#Milzvergrößerung#Splenektomie#Milzentfernung#linker Leberlappen#Hepatitis*#Leberentzündung#Hepatose*#Leberschädigung#nicht entzündliche Lebererkrankung#Steatosis hepatis*#Fettleber#Leberverfettung#Hepatomegalie*#Lebervergrößerung#Schrumpfleber, Spätstadium der Leberfibrose#Hepatopathie*#Leberkrankheit#Leberinsuffizienz#Leberversagen#Hepatotoxizität#Leberschäden#Lebervergiftung#hepatotoxisch*#leberschädigend#Aszites#Bauchwassersucht#Wasserbauch#Tremor*#Zittern#Chole#Bilis#Fel#Cholesterin#Galle#Gallenflüssigkeit #Blutfette#Vesica biliaris#Vesica fellea#Gallenblase#Arteria cystica*#Gallenblasenschlagader#Cholezystitis*#Gallenblasenentzündung#Cholezystektomie#Gallenblasenentfernung#Hyperhidrose#Fehlende#Verminderte#vermehrte Schweißbildung#Leberfibrose#krankhafter Umbau von Lebergewebe in Bindegewebe#Leberzirrhose#Cholezystolithiasis#Canalis#Kanal#Ductus hepaticus dexter#sinister#rechter#linker Lebergang#Ductus hepaticus communis#gemeinsamer Lebergang#Ductus cysticus*#Gallenblasengang#Ductus choledochus*#Hauptgallengang#Cholangitis*#Gallengangentzündung#Cholangiokarzinom#Gallengangkrebs#Cholelithiasis*#Gallensteinleiden#Choledocholithiasis*#Hauptgallengangsteinleiden#Lithos#Konkrement*#Stein#Cholelitholyse#Cholelithotripsie#medikamentöse Auflösung#Zertrümmerung der Gallensteine"
let randomWords17 = "Cholestase*#Gallenstau#Cholezystographie#Röntgenkontrastdarstellung der Gallenblase#Cholangiographie#Röntgenkontrastdarstellung der Gallengänge#Bilirubin*#Gallenfarbstoff#Intestinum#Darm#Enteron#Intestinum tenue*#Dünndarm#Duodenum*#Zwölffingerdarm#Duodenitis#Zwölffingerdarmentzündung#Jejunum*#Leerdarm#Ileum*#Krummdarm#Colon#Intestinum crassum*#Dickdarm#Grimmdarm#Caecum#Zäkum#Typhlitis*#Blinddarm#Blinddarmentzündung#Appendix vermiformis*#Wurmfortsatz des Blinddarms#Appendizitis#Appendektomie*#Wurmfortsatzentzündung#Wurmfortsatzentfernung#vermiformis*#wurmförmig#wurmartig#Colon ascendens#aufsteigender Dickdarm#Colon transversum#querer Dickdarm#Colon descendens#absteigender Dickdarm#Colon sigmoideum#Sigma#s-förmiger Dickdarm#Kolonkarzinom*#Dickdarmkrebs#Megakolon#Dickdarmerweiterung#Colon irritabile#Colitis spastica#Reizdarmsyndrom#Morbus Crohn#Colitis ulcerosa*#chronisch entzündliche Darmerkrankung (CED)#Koloskopie#Dickdarmspiegelung#Rektum#Proktos#Mastdarm#Proktitis*#Mastdarmentzündung#Rektumprolaps*#Mastdarmvorfall#Rektumkarzinom*#Mastdarmkrebs#kolorektales Karzinom*#Dickdarm- und Mastdarmkrebs#Anus*#After#Darmausgang#Proktoskopie#Analkanalspiegelung#Sphinkter*#Schließmuskel#Ringmuskel#Analfistel#unnatürlicher Gang neben dem After#Analfissur#Afterriss#Schleimhauteinriss des Afters#Hämorrhoiden*#Venenerweiterungen im Afterbereich#Analprolaps*#Vorfall der Haut des Afters#Crena analis#Rima ani#Gesäßspalte#Afterspalte#Gesäßbacken#Gesäßhälften#Gesäße#Nates#Clunes#Defäkation*#Darmentleerung#Stuhlgang#Stuhlausscheidung#Faeces#Fäzes#Stuhl#Kot#Meläna*#Teerstuhl#Hämatochezie#Blutstuhl#Enterostoma#Ileostoma#Anus praeter#künstlicher Darmausgang#Stoma#Öffnung#Peritoneum*#Bauchfell#Peritonitis*#Bauchfellentzündung#Omentum minus#majus*#kleines#großes Bauchnetz#Darmnetz#Mesenterium*#Gekröse#Dünndarmgekröse#Adipositas#Adipös#Lipos#Lipid,#Adeps *#Fettsucht#Fettleibigkeit#Fettsüchtig#Fettleibig#Fett#Lipom#gutartige Fettgeschwulst#Physiologie#Digestion*#Verdauung#Metabolismus#Stoffwechsel#Anabolismus#Aufbaustoffwechsel#Katabolismus#Abbaustoffwechsel#Absorption#Resorption#Nährstoffaufnahme#Malabsorption#gestörte Nährstoffaufnahme#Pathologie#Gastroenteritis#Magen-Darm-Grippe#Magen-Darm-Entzündung#Enteritis*#Dünndarmentzündung#Enterocolitis#Kolitis*#Dünndarm- und Dickdarmentzündung#Dickdarmentzündung#Zöliakie*#Glutenunverträglichkeit#Dysenterie#Ruhr, bakterielle Darmentzündung#Amöbiasis*#Amöbenruhr#Fistel#unnatürliche Verbindung zwischen Hohlorganen"
let randomWords18 = "Anastomose#künstliche Verbindung zwischen Hohlorganen#Lumen#Hohlraum#Gastrektasie#Magenerweiterung#Symptom#Nausea*#Übelkeit#Brechreiz#Vomitus#Emesis#Hyperemesis#Erbrechen#Kotzen#übermäßiges Erbrechen#Hämatemesis*#Bluterbrechen#Kaffeesatzerbrechen#Singultus*#Schluckauf#Anorexie#Inappetenz*#Appetitverlust#Appetitlosigkeit#Anorexia nervosa#Magersucht#Diarrhoe*#Durchfall#Steatorrhoe#Fettstuhl#Obstipation*#Verstopfung#Flatus#Wind#Flatulenz#Blähung#Meteorismus#Blähsucht#Blähungen#Tenesmus ani#vesicae#schmerzhafter Stuhldrang#Harndrang#Polydipsie#Trinkzwang#gesteigerter Durst#Polyphagie#Hyperphagie#Fresssucht#gesteigerter Hunger#Gefräßigkeit#Bulimie#Bulimia nervosa#Ess–Brech–Sucht#Dysphagie#Dyskatabrosis*#Schluckstörung#Hypogastrium#Unterbauch#Regio pubica#Schamregion#Dyspepsie*#Verdauungsstörung#Odynophagie#Ösophagodynie#schmerzhaftes Schlucken#operative Eröffnung der Bauchhöhle#Abdomensonographie#Ultraschalluntersuchung des Bauches#Dermatologie#Cutis#Derma*#Haut#Dermatitis*#Hautentzündung#Dermis#Lederhaut#Epidermis#Oberhaut#Perkutan#transdermal#durch die Haut#intrakutan*#in die#in der Haut#subkutan*#unter der Haut#unter die Haut#subkutane Injektion#Einspritzung in das Unterhautfettgewebe#Intramuskulär#i.m*#in den Muskel#peroral#Gallenblasensteinleiden#Ductus#Gang#durch den Mund#parenteral#enteral#Nahrungsaufnahme als Infusion#orale Nahrungsaufnahme#Tunica mucosa*#Schleimhaut#Textus connectivus#Bindegewebe#Dermatose#Hautkrankheit#Hämatom*#Bluterguss#Hämangiom, Angiom*#Blutschwamm#gutartige Gefäßgeschwulst#Nävus*#Muttermal#`Leberfleck`#Nävus flammeus#vinosus*#Feuermal#Spidernävus#Spinnennävus#Leberhautzeichen#Melanom*#schwarzer Hautkrebs#Spinaliom*,#Plattenepithelkarzinom#heller Hautkrebs#Basaliom#Basalzellenkarzinom*#weißer Hautkrebs#Vitiligo#Weißfleckenkrankheit#Albinismus#Weißsucht#angeborener Hautfarbstoffmangel#Dermatitis solaris#Sonnenbrand#Psoriasis vulgaris*#Schuppenflechte#Ekzem*#Juckflechte#juckender Hautausschlag#Heliosis#Insolation#Sonnenstich#Hitzschlag#Tinea pedis#Fußpilz#Genital-#Oncho- mykose#Genital- #Nagel- pilz#Pruritus*#Juckreiz, Hautjucken#Immunität#Abwehr#Unempfindlichkeit#Allergie#Überempfindlichkeit#anaphylaktischer Schock#schweres allergisches Kreislaufversagen#Urtikaria*#Nesselsucht#Ikterus*#Gelbsucht#Exanthem#Hautausschlag#Komedo(nen)*#Mitesser#Atherom*#Grützbeutel#Läsion#Verletzung#Schädigung#Erosion#Exkoriation*#Hautabschürfung#Hautdefekt#Pilus(Pili)#Haar(e)#Alopezie*#Haarausfall#Squama*"
let randomWords19 = "Schuppe#Hautschuppung#Crusta#Kruste#Pickel#Hepar*#Leber#Lobus hepatis dexter#sinister#rechter #Eiterbläschen#Erysipel*#Wundrose#Erysipeloid#Rotlauf#Zellulitis#Phlegmone#Entzündung des Zellgewebes #diffuse eitrige Entzündung des#Bindegewebes#Cellulite#dellenförmige Hautoberfläche#Peau d´ orange#Orangenhaut#Verruca(e)*#Warze(n)#Verruca plantaris#Dornwarze#Fußsohlenwarze#Verruca vulgaris#Hautwarze#Schorf#Borke#Pustel#Hautärztin#Dermatologie#Lehre von Hauterkrankungen#Endokrinologie & Drüse #Hormonalsystem#Endokrinologie#Hormonlehre#Glandula(e)*#Drüse(n)#Adenitis#Drüsenentzündung#Thalamus*#Sehhügel#Glandula pituitaria, Hypophyse *#Hirnanhangsdrüse#Glandula pinealis#Epiphyse *#Zirbeldrüse#Glandula thyreoidea*#Schilddrüse#Hyperthyreose*#Schilddrüsenüberfunktion#Hypothyreose*#Schilddrüsenunterfunktion#Euthyreose#normale Schilddrüsenfunktion#Struma*#Kropf#Vergrößerung der Schilddrüse#Thyreoiditis#Schilddrüsenentzündung#Thyreoidektomie#Schilddrüsenentfernung#Glandula parathyreoidea#Nebenschilddrüse#Hyperparathyreoidismus*#Nebenschilddrüsenüberfunktion#Hypoparathyreoidismus*#Nebenschilddrüsenunterfunktion#Thymus#Bries#Glandula suprarenalis#adrenalis *#Nebennierendrüse#Cortex glandulae suprarenalis#Nebennierenrinde#Adrenalektomie#Nebennierenentfernung#Saliva#Sialon*#Speichel#Salivation*#Speichelfluss#Sialolithiasis#Speichelsteinleiden#Sialoadenitis#Speicheldrüsenentzündung#Glandula salivaria (Glandulae salivariae)#Speicheldrüse(n)#Parotis#Glandula parotidea, parotis#Ohrspeicheldrüse#Parotitis #Mumps#Parotitis epidemica*#Ohrspeicheldrüsenentzündung#Ziegenpeter#Glandula submandibularis#Unterkieferspeicheldrüse#Glandula sublingualis#Unterzungenspeicheldrüse#Pankreas*#Akromegalie#Vergrößerung der Körperendteile#Acrum, Akre(Akren)#stammferne Körperspitze(n)#Extremitätenende(n)#Hirsutismus#vermehrte Behaarung#Rachitis#Vitamin-D-Mangel-Krankheit#Skorbut#Vitamin-C-Mangel-Krankheit#CT#Computertomographie#computergestütztes Schichtaufnahmeverfahren#MRT#Magnetresonanztomographie#Kernspintomographie#computergestütztes Schichtaufnahmeverfahren mit Magnetresonanz#Sonographie#Ultraschalluntersuchung#Duplexsonographie#farbkodierte Ultraschalluntersuchung#Szintigraphie#bildliche Darstellung mit Hilfe von radioaktiven Substanzen#Nephrologie & Harnsystem#Andrologie & männliches Genitalsystem#Andrologie#Männerheilkunde#Ren#Nephros*#Niere#Nephritis*#Nierenentzündung#Nephrektomie*#Nierenentfernung#Nephrolithiasis#Urolithiasis*#Nierensteinleiden#Harnsteinleiden"
let randomWords20 = "Ureterolithiasis*#Harnleitersteinleiden#Hydronephrose#Wassersackniere#Harnstauungsniere#Nephroptose#Senkniere#Wanderniere#nephrotoxisch*#nierenschädigend#nierengiftig#Nephropathie#Nierenerkrankung#Glomerulus#Knäulchen#kleines Knäuel#Pyelon#Pelvis renalis*#Nierenbecken#Pyelonephritis#Pyelitis*#Nierenbeckenentzündung#Ureter#Hydroureter *#Harnleiter#Harnleitererweiterung#Ureterstenose*#Harnleiterverengung#Megaureter#Harnleitervergrößerung#Vesica urinaria*#Harnblase#Harninkontinenz#Blasenschwäche#ungewollte Harnabgang#Urgeinkontinenz#ungewollter Harnabgang bei starkem Harndrang#Stressinkontinenz#ungewollter Harnabgang unter Belastung#Zystitis#Harnblasenentzündung#Zystoskopie*#Blasenspiegelung#Zystektomie*#Blasenentfernung#Urethra*#Harnröhre#Harnsamenröhre#Urethritis*#Harnröhrenenentzündung#Harnsamenröhrenentzündung#Urethrastriktur#Harnröhrenverengung#Urethroskopie*#Harnröhrenspiegelung#Miktion#Miktio*#Wasserlassen#Harnlassen#Blasenentleerung#Urin#Harn#Hämaturie*#Blut im Harn#Pyurie#Eiterharn#Bakteriurie#Bakterien im Urin#Spermaturie#Spermen im Urin#Proteinurie#Eiweiß im Urin#Glukosurie#Urinzucker#Zucker im Urin#Dysurie#Algurie#schmerzhaftes Wasserlassen#Strangurie#Harnzwang#Nykturie*#nächtliches Wasserlassen#Pollakisurie*#häufiges Wasserlassen#Polyurie#vermehrte Harnmenge#Oligurie#Anurie#verminderte Harnmenge#Harnretention#Ischurie*#Harnverhaltung#Harnsperre#Retention#Züruckhaltung#Residualharn#Restharn#Diurese#Harnausscheidung#Enuresis nocturna#nocturnus#Bettnässen#Einnässen#nachts#Urosepsis#Nierenvergiftung#Urea#Carbamid#Harnstoff#Urämie*#Harnvergiftung#Hyperurikämie*#erhöhter Harnsäurespiegel im Blut#Niereninsuffizienz*#Nierenversagen#Nierenfunktionsstörung#Nephrologe*#Facharzt für Nierenerkrankungen#Nephrologie*#Lehre von den Nierenerkrankungen#Orchis#Testis#Didymus*#Hoden#Orchitis#Didymitis#Hodenentzündung#Hodentorsion#Hodenverdrehung#Orchiektomie#Hodenentfernung#Kryptorchismus*#Hodenhochstand#Orchidopexie*#Hodenbefestigung#Fixierung des Hodens#Anorchie*#angeborenes Fehlen der Hoden#Seminom#bösartige Hodengeschwulst#Epididymis*#Nebenhoden#Epididymitis*#Nebenhodenentzündung#Epididymektomie#Nebenhodenentfernung#Skrotum*#Hodensack#Glandula prostatica#Prostata*#Vorsteherdrüse#Prostatitis*#Vorsteherdrüsenentzündung#Prostatakarzinom#Vorsteherdrüsenkrebs#Vesicula seminalis*#Samenbläschen#Bläschendrüse#Colliculus seminalis*#Samenhügel#Ductus#Tuba#Vas deferens*#Samenleiter#Ductus ejaculatorius*#Spritzkanal"
let randomWords21 = "Sperma#Samen#Samenflüssigkeit#Spermium(Spermien)*#Samenzelle(n)#Samenfaden#reife männliche Keimzelle(n)#Penis, Phallus*#männliches Glied#Glans penis*#Eichel#Balanitis*#Eichelentzündung#Präputium*#Vorhaut#Phimose#Vorhautverengung#Posthitis#Vorhautentzündung#Zirkumzision#Beschneidung der Vorhaut#Erektion*#Aufrichtung#Anschwellung von Penis oder Klitoris#Ejakulation*#Samenerguss#Ejaculatio praecox#retarda#vorzeitiger#verzögerter Samenerguss#Priapismus#schmerzhafte Dauererektion#Impotenz#Unvermögen#Unfähigkeit#Kastration#Entfernung der Keimdrüsen#Gonaden#Keimdrüsen#Geschlechtsdrüsen#Hoden + Eierstock#Chirurgie#Inzisur#Incisura*#Einschnitt#Einbuchtung#Inzision#inzidieren*#operativer Schnitt#Einschnitt #einschneiden#Exzision#exzidieren*#Ausschneidung#Entfernung #herausschneiden#Resektion#resezieren*#operative Teilentfernung#teilweise entfernen#Exstirpation#operative Vollentfernung#Extraktion#Laparoskopie*#Bauchspiegelung#Laparotomie#Abtragung#Entfernung#Histo#Gewebe#Biopsie*#Gewebeentnahme#Gewebeprobenentnahme#Exzisionsbiopsie#vollständige Entnahme der Gewebeveränderung#Inzisionsbiopsie#Entfernung eines Teils der Gewebeveränderung#Intubation#Drainage#Einführung eines Rohres#Ableitung#Hernie*#Bruch#Eingeweidebruch#Weichteilbruch#Hiatushernie#Hernia#diaphragmatica*#Zwerchfellbruch#Hiatus*#Öffnung#Hernia femoralis*#Schenkelbruch#Hernia inguinalis*#Leistenbruch#Hernia umbilicalis*#Nabelbruch#Narbenhernie#Narbenbruch#Varix#Varize(Varizen)#Krampfader (Krampfadern,Venenknoten)#Varikosis#Varikose*#Krampfaderleiden#Krampfadern#Varikozele*#Krampfaderbruch#Hodenkrampfader#Hydrozele*#Wasserbruch#Hydrozele testis#Hodenwasserbruch#Flüssigkeitsansammlung im Hodensack#Hydrozele funiculi#Flüssigkeitsansammlung im Samenstrang#Inkarzeration#inkarzeriert*#Einklemmung einer Hernie#eingeklemmt#Volvulus#Sigmavolvulus*#Darmverdrehung#Darmverschlingung#Verdrehung des s-förmigen#Dickdarms#Haustrum(en)#Ausbuchtung(en) der Dickdarmwand#Polyp#Polyposis#Schleimhautvorwölbung#zahlreiche Schleimhautvorwölbungen#Polypektomie#Entfernung einer Schleimhautvorwölbung#Invagination#Intussuszeption#Darmeinstülpung#Divertikel#Diverticulum#Darmausstülpung#Darmaussackung#Divertikulose*#zahlreiche Darmausstülpungen#Darmaussackungen#Divertikulitis#Entzündung einer Darmausstülpung#Darmaussackung#Ileus#mechanischer Ileus *#Darmverschluss#paralytischer Ileus#Darmlähmung#Darmstillstand#Adhäsion*#Verwachsung#Verklebung#Prolaps*#Vorfall#Amputation#Implantation#Abtrennung"
let randomWords22 = "Entfernung#Einpflanzung#Nekrose*#Örtlicher#lokaler Gewebetod#Gangrän#Wundbrand#Gewebenekrose#Ulcus#Ulkus(Ulcera)*#Geschwür(e)#Ulcus cruris*#Unterschenkelgeschwür#Dekubitus*#Druckgeschwür#Wundliegegeschwür#Clavus*#Hühnerauge#Hornauge#Callus#Hornschwiele#Dehydration#Exsikkose#exsikkiert#Austrocknung#ausgetrocknet#Kachexie#Auszehrung#starke Abmagerung#Ödem#Wassersucht#Wassereinlagerung#Wasseransammlung#Pus#Pyon#purulent*#Eiter#eitrig#Abszess#abgekapselte Eiteransammlung#Empyema#Empyem#Eiteransammlung in einer Körperhöhle#Zyste#gekapselter flüssigkeitsgefüllter Hohlraum im Gewebe#Sinus pilonidalis#Steißbeinfistel#Haarnestzyste#Bulla#Cutis bulla*#Blase#Hautblase#Vesicula#vesikulär#Bläschen#Bläschenförmig#bläschenartig#Agonie*#Todeskampf#Vulnus#Wunde#Erythem#Hautrötung#Hyperämie#Mehrdurchblutung#Sekret(e)#Absonderung(en)#Trepanation*#operative Eröffnung der Schädelhöhle#Kraniotomie*#operative Eröffnung des Schädels#benigner#maligner Tumor#gutartige#bösartige Geschwulst#Schwellung#Verdickung#Benigne#maligne*#gutartig#bösartig#Karzinom#bösartige Geschwulst des Epithelgewebes#Sarkom#bösartige Geschwulst des Bindegewebes#karzinogen#kanzerogen#krebserregend#krebserzeugend#Pathologie#pathologisch#Krankheitslehre#krankhaft#Induration#Fibrose#Gewebeverhärtung#Genese#Entstehung#Involution#Regression#regressiv*#Rückbildung, Rückentwicklung#s. zurückbildend,#s. zurückentwickelnd#Evolutio#Progression#Progressiv#progredient*#Entwicklung#Fortschreiten#fortschreitend#Atrophie#Gewebeschwund#Atrophieren#atrophiert#atrophisch#schrumpfen#geschrumpft#schwindend#Hypertrophie#hypertroph#Gewebevergrößerung#vergrößert#Aplasie*#Nichtausbildung#Dysplasie*#Fehlbildung#Neoplasie*#Neubildung#Dystrophie#Fehlwuchs#Metastase(n)#Filiae(Pl.)#Tochtergeschwulst(ülste)#Tumorabsiedelung#Chirotherapie#manuelle Therapie#manuelle Medizin#Radiotherapie#Radiologie#Strahlentherapie#Strahlenlehre#Onkologie#Lehre von den Geschwulsterkrankungen#Onkologe*#Krebsspezialist#Facharzt für Geschwulsterkrankungen#Restitutio*#Wiederherstellung#Richtung & Bewegung#Lage- und Richtungsbezeichnung#Anterior#anterius#vorne gelegen#vorder#vorne#posterior#posterius#hinten gelegen#hinter#superior*#oben gelegen#ober#inferior#unten gelegen#unter#median#in der Mitte#medial#zur Mitte hin gelegen#in Richtung Körpermitte#lateral#seitlich gelegen#dorsal#rückenseitig#in Richtung Rücken#ventral*#bauchseitig#in Richtung Bauch#proximal*#körpernah#in Richtung Rumpf#distal"
let randomWords23 = "körperfern#in Richtung Extremitätenende#kranial*#schädelwärts#in Richtung Kopf#kaudal*#schwanzwärts#steißwärts#in Richtung Becken#profundus*#tief gelegen#basilar#grundlegend#Herausziehen#Ablatio#Ablösung#Abtrennung#rectus*#gerade#unilateral#semilateral#bilateral *#einseitig#halbseitig#beidseitig#ipsilateral#homolateral#kontralateral#auf der gleichen Seite#auf der Gegenseite#konträr*#entgegengesetzt#intern*#innerlich#von innen#extern*#äußerlich#von außen#dexter#dextra#sinister,#sinistra*#rechts#links#Bewegung#Abduktion*#Wegführung#Abspreizen einer Extremität nach außen#Adduktion#Heranführung einer Extremität zur Körpermitte#Extension*#Streckung#Extensor#extendere*#Streckmuskel#Strecker#ausstrecken#Flexion*#Beugung#Biegung#Flexor#Beugemuskel#Bieger#Rotation#Drehung#Rotation externus#Auswärtsdrehung#Rotation internus#Einwärtsdrehung#Rotation mediales#Drehbewegung zur Mitte#Rotation laterales#Drehbewegung nach außen#Supination#Auswärtsdrehung#Pronation*#Einwärtsdrehung#Elevation#elevare*#Anhebung #anheben#Inklination#inklinieren#Vorbeugung der Wirbelsäule#vorbeugen#Reklination#reklinieren*#Rückbeugung#Streckung der Wirbelsäule#zurückbeugen#afferens#afferent*#hinführend#zuführend#heranführend#efferens#efferent*#wegführend#herausführend#importieren#exportieren*#hinführen#ausführen#ascendens#descendens#deszendierend#aufsteigend#absteigend#Infektionen#Infektion#Infektiös#infiziert*#Ansteckung#Ansteckend#angesteckt#Kontagiosität#Ansteckungskraft#Übertragungsfähigkeit#Ätiologie#Kausal#ätiologisch*#Krankheitsursachen#Ursache#ursächlich#idiopatisch*#ohne erkennbare Ursache#Kontamination*#Verschmutzung#Verunreinigung#Mikroorganismus(Mikroorganismen)#Erreger#Intoxikation*#Vergiftung#zytotoxisch*#zellschädigend#Apathie#apathisch#Teilnahmslosigkeit#teilnahmslos#Fatigue#Malaise*#Erschöpfung#Ermüdung#Ermattung#chronische Müdigkeit,#Abgeschlagenheit#Schlappheit#Adynamie#adynamisch*#Antriebslosigkeit#Kraftlosigkeit#antriebslos#Pyrexie#Febris*#Fieber#Afebril#febril*#ohne Fieber#fieberfrei#fieberhaft#paroxysmal#anfallsartig#plötzlich#anfallsweise#in Anfällen#Rubella#Rubeola*#Röteln#Masern*#Morbilli#Varizellen#Variola*#Windpocken#Wasserpocken#Pocken#Herpes#Herpes zoster*#Bläschenanschlag#Gürtelrose#Scarlatina*#Scharlach#infektiöse Mononukleose*#pfeiffersches Drüsenfieber#Gonorrhoe*#Tripper#Syphilis#Syphilus*#Lues#harter Schanker#Maselsucht#Ulcus molle*#weicher Schanker#Rabies#Lyssa*#Tollwut#Wutkrankheit#Tetanus*"
let randomWords24 = "Wundstarrkrampf#Poliomyelitis*#Kinderlähmung#Pertussis*#Keuchhusten#Diphterie#Halsbräune#Lepra#Morbus Hansen *#Aussatz#Miselsucht#Skabies*#Krätze#Pest#schwarzer Tod#Tularämie#Hasenpest#Nagetierseuche#Anthrax*#Milzbrand#Brucellose#Brucella#Maltafieber#Mykose*#Pilzinfektion#Malaria*#Wechselfieber#Neonatologin#Pädiater#Pädiatrie*#Fachärztin für Neugeborene#Kinderarzt#Kinderheilkunde#Medikamente#Therapie#medizinische Behandlung#Prophylaxe#Prävention#prophylaktisch*#Vorbeugung#Verhütung#vorbeugend#Inhibition#Inhibitor#inhibieren*#Hemmung#Hemmer#Blocker#Hemmstoff#Hemmen#hindern#Zytostatika#Krebsmittel#Zellwachstum hemmende Mittel#Vakzination#Vakzin(e)#Impfung#Impfstoff(e)#Antidot*#Gegenmittel#Gegengift#Plazebo#Scheinarzneimittel#Scheinmedikament#Synthetisch#artifiziell*#künstlich#kurabel#inkurabel*#heilbar#unheilbar#kurativ#palliativ#heilend#lindernd#nicht heilend#symptomatische Therapie#reversibel#irreversibel*#umkehrbar#nicht umkehrbar#kompatibel#compati*#vereinbar#verträglich#kombinierbar#zusammen passend#inkompatibel*#unvereinbar#unverträglich#nicht kombinierbar#nicht zusammen passend#fungizid#Fungizid(e)#Fungi(Pl.)*#Pilztötend#Pilze abtötend#pilztötendes Mittel#Pilze#Indikation#Heilanzeige#Kontraindikation#Gegenanzeige#Reaktion#Interaktion#Gegenwirkung#Wechselwirkung#Anästhesie*#Lokalanästhesie*#örtliche Betäubung#Narkose#allgemeine Betäubung#Anästhetikum*#Betäubungsmittel#Narkosemittel#Hypnotikum#Schlafmittel#Sedativum#Tranquilizer#Sedierung#Beruhigungsmittel#Beruhigung#Relaxans(Relaxanzien)#Muskelrelaxans#Entspannungsmittel#Muskelerschlaffungsmittel#Hämostatikum#Hämostyptikum*#blutstillendes Mittel#Antikoagulation*#Blutverdünnung#Gerinnungshemmung#Antikoagulans#Antithrombotikum#Heparin*#Blutverdünner#gerinnungshemmendes Mittel#Transfusion#Donor*#Blutübertragung#Spender#Analgetikum(Analgetika)#Analgesie*#Schmerzmittel#Schmerzbekämpfung#Antiphlogistikum*#Entzündungshemmer#entzündungshemmendes Mittel#Antipyretikum(Antipyretika) *#Fiebermittel#Antibiotikum(Antibiotika)#Mittel gegen Krankheitserreger#Antiseptikum#keimtötendes Mittel#Antimykotikum#Antipilzmittel#Antiemetikum(Antiemetika)#Mittel gegen Übelkeit und Erbrechen#Emetikum(Emetika)#Brechmittel#Antazidum(Antazida)#Magensäuremittel#Protonenpumpeninhibitor#-blocker (PPI)#Magenschutz#Magensäureblocker#Laxativum#Laxans(Laxantien)#Abführmittel#Antidiarrhoika#Medikamente gegen Durchfall#Spasmolytikum#Krampflöser#krampflösendes Mittel#Antihypertonikum(Antihypertonika)#ACE-"
let randomWords25 = "Hemmer#Blutdruckmittel#Blutdrucksenkmittel#Mittel gegen Bluthochdruck#Antihypotonika#Kreislaufmittel#Vasodilator#Dilatation*#Gefäßerweiterungsmittel#Erweiterung#Vasokonstriktor#Gefäßverengungsmittel#Diuretikum(Diuretika)#Wassertablette, Entwässerungsmittel#Antiarrhythmikum#Mittel gegen Herzrhythmusstörungen#Kardiaka#Herztabletten#Antidepressivum(Antidepressiva)#stimmungshebendes Mittel#Anxiolytikum#angstlösendes Mittel#Antikonvulsivum#Mittel gegen Krampfanfälle#Antitussivum(Antitussiva)#Hustenstiller#Hustenmittel#Hustensaft#Expektorans#Hustenlöser#Mittel zur Förderung des Auswurfs#Mukolytikum#Schleimlöser#schleimlösendes Mittel#Konzeption#Antikonzeption#Kontrazeption*#Befruchtung#Empfängnis#Empfängnisverhütung#Kontrazeptivum#Antikonzeptivum*#Verhütungsmittel#Anti Baby Pille#Tokolyse#Tokolytikum*#Wehenhemmung#Wehenhemmer#Ovulationshemmer*#Eisprunghemmer#L-thyroxin#Medikament für Schilddrüsenunterfunktion#Insulin#Medikament für Zuckerkrankheit#Kortikoide, Kortikosteroide#Medikamente, die den Hormonen der Nebennierenrinde#ähneln#Lipidsenker#Fettsenker#Suppositorium#Zäpfchen#Dermatika#Salben#Phytotherapie#Pflanzenheilkunde#Weitere#Rekonvaleszenz*#Genesung#Erholung#Besserung#Gesundung#Reanimation#reanimieren#Wiederbelebung#wiederbeleben#Remission#vorübergehende Verbesserung der Krankheitssymptome#Abklingen#Nachlassen#Rückgang#Emission#Ausstoß#Radiatio*#Bestrahlung#Permeabilität#permeabel#Durchlässigkeit#durchlässig#Atrepsie, Marasmus#Gedeihstörung#Immobilisation#Immobil#mobil*#Ruhigstellung#Unbeweglichkeit#Unbeweglich#Beweglich#Disaccharid#Zweifachzucker#Laktose*#Milchzucker#Monosaccharid#Einfachzucker#Fruktose#Fruchtzucker#Glukose#Dextrose*#Traubenzucker#Stärkezucker#Ferrum*#Eisen#Sideropenie*#Eisenmangel#bougieren#aufdehnen#Adoleszenz#Jugendalter#Geron#Senium#senil#Greis#Alter#Greisenalter#greisenhaft#Geriatrie#Geriater#Altersheilkunde#Altmediziner#Facharzt für Erkrankungen bei älteren Menschen#Mors#Exitus#Tod#letal*#tödlich#moribund*#sterbend#Suizid*#Selbstmord#Rigor mortis*#Todenstarre#Leichenstarre#Obduktion#Autopsie#Sektion#Leichenschau#Psyche#Psychiatrie#Seele#Seelenheilkunde#Depression*#krankhafte Niedergeschlagenheit#depressiv#deprimiert*#niedergeschlagen#Melancholie#Traurigkeit#Schwermut#Trübsinn#Phobie#krankhafte Angst#Furcht#Photophobie#Lichtscheu#Lichtüberempfindlichkeit#Phonophobie#Lärmüberempfindlichkeit#Klaustrophobie#Raumangst#Platzangst#Abusus#Missbrauch#Karenz#Verzicht#Enthaltsamkeit#Noxe(n)"
let randomWords26 = "Schadstoff(e)#lokalisiert#örtlich begrenzt#Inflammatio*#Entzündung#Calor#Rubor#Dolor#Pallor*#Wärme#Überwärmung#Rötung#Schmerz#Blässe#Dolent# dolorosus*#schmerzhaft#indolent*#schmerzlos#undulierend#ondulierend*#wellenförmig#Kausalgie#brennender Schmerz#Morbus#Nosos#Pathos#Krankheit#Erkrankung#kongenital#angeboren#Tonus#Spannung#verus*#wahr#echt#Hygiene#Gesundheitslehre#Hypothermie#Unterkühlung#Accidens#akzidentiell*#zufällig#Circulus#Ring#Persistierend#Persistent#permanent*#dauerhaft#andauernd#fortbestehend#anhaltend#bleibend#fugax#transient#transitorisch#temporär*#vorübergehend#Anamnese*#Krankenvorgeschichte#Aufnahmegespräch#Korperliche Untersuchung#Inspektion#Betrachten#Palpation#Abtasten#Auskultation#auskultieren#Abhören#Abhorchen#Abhören#abhorchen#Perkussion#Abklopfen#Befund#Untersuchungsergebnis#postprandial*#nach der Nahrungsaufnahme#alimentär#ernährungsbedingt#Natriumchlorid*#Kochsalz#vanus, frustran#vergeblich#ohne Ergebnis#infaust#hoffnungslos#aussichtslos#Diameter#Durchmesser#completus*#vollständig#partial, partiell#teilweise#terminal#final#initial#im Endstadium#anfangs#iatrogen#durch den Arzt verursacht#auxiliär#adjuvant#helfend#unterstützend#fortis#mitis#stark#schwach#prominent#aus etwas hervorragend#substituieren#Substitution*#Ersetzen#Ersatz#invasiv#in den Körper eindringend#eingreifend#konstant*#stetig#gleichbleibend#beständig#alternierend*#abwechselnd#abwechelseitig#Genetik#Gen#Hereditär#genetisch*#Vererbungslehre#Erbanlage#erblich#Dysfunktion#Funktionsstörung#Dissemination*#Ausbreitung#Irritation#Irritiert#Blande#Stimulus*#Reizung#Gereizt#Reizlos#Reiz#Exzitation#Erregung#Agitiertheit#Agitation#agitiert*#Erregungszustand#erregt#Dilution#diluere*#Verdünnung #verdünnen#Kolik#krampfartige Schmerzen#Inzidenz#Prävalenz*#Neuerkrankungsrate#Krankheitshäufigkeit#Obstruktion*#Verschluss#Liquid#Humor*#Flüssig#Flüssigkeit#Konfluieren#konfluierend#zusammenfließen#zusammenfließend#Akkumulation#accumulare#Anhäufung#Anhäufen#ansammeln#Prognose#Diagnose#Vorhersage#Heilungsaussicht#Feststellung einer Krankheit#akut*#plötzlich auftretend#schnell verlaufend#chronisch#lang andauernd#anhaltend#langsam s. entwickelnd#latent#symptomlos verlaufend#verborgen#intermittierend#mit Unterbrechungen auftretend#Rezidiv#Relaps#rezidivierend#Rückfall#Wiederauftreten einer Krankheit #Wiederkehrend#wiederauftretend#Exazerbation#Verschlimmerung einer Krankheit#Occultus#okkult*#verborgen, nicht sichtbar#Fecal Occult Blood Test (FOBT)"
let randomWords27 = "Test auf verborgenes Blut im Stuhl#Artefakt#künstliche Messstörung#Azidose#Alkalose#Übersäuerung#Basenüberschuss#Anfänge & Enden#-itis#Entzündung → Gastritis#Dys-#Störung → Dysphagie#-pathie#Krankheit → Nephropathie#-Om / Karzinom#Krebs → Basaliom#Kolonkarzinom#-skopie#Spiegelung → Ösohagoskopie#-lithiasis#Steinleiden → Choletithiasis#-ektomie#Entfernung → laryngektomie#-ämie#Stoffe im Blut → Hperglykämie#insuffizenz#Schwäche → Herzinsuffizenz#Hyper- #Hypo-#vermehrt Überfunktion → Hyperthyreos vermindert Untenfunktion → Hypothyreos -ose#degenrativ chronische Zustände → Arthrose#Intra- x extra-#innerhalb x außerhalb → Intrakranial#-opexie#Befestigung#supra*#infra#super#oberhalb#unterhalb#über#-pnie#Mangel → Leucopnie#Articulatio-#Gelenk → Articulatio cubiti#Algie#dynie#Schmerz → Arthalgie#Otodynie#-tase#Stauung → Cholestase#-koilk#krampfartige Schmerzen → Nierenkolik#-opie#Auge betreffed → Emetropie#-spasmus#Muskelkrampf → Pylorospasmus#-ual#Zunge betreffed → lingual#-megalie#Vergrößerung → Akromegalie#-urie#Harn betreffed → Pyurie#-parese#Lähmung → Gastroparese#-stenose#Verengung → Ureterstenose#-ästhesie#Empfindung → Hyperästhesie#-Makro#Vergroßung → Makroglossie#-loge#Arzt für  #arzt→ Onkologe#-Mikro#Kleinheit → Miktostomie#-ologie#heilkunde#Lehre von, Fachgebiet für#Netzhauterkrankung#Choroidea*#Aderhaut des Auges#Sclera*#Lederhaut des Auges#Lens oculi#Phakos"

let randomWordsArr1 = randomWords1.split("#");
let randomWordsArr2 = randomWords2.split("#");
let randomWordsArr3 = randomWords3.split("#");
let randomWordsArr4 = randomWords4.split("#");
let randomWordsArr5 = randomWords5.split("#");
let randomWordsArr6 = randomWords6.split("#");
let randomWordsArr7 = randomWords7.split("#");
let randomWordsArr8 = randomWords8.split("#");
let randomWordsArr9 = randomWords9.split("#");
let randomWordsArr10 = randomWords10.split("#");
let randomWordsArr11 = randomWords11.split("#");
let randomWordsArr12 = randomWords12.split("#");
let randomWordsArr13 = randomWords13.split("#");
let randomWordsArr14 = randomWords14.split("#");
let randomWordsArr15 = randomWords15.split("#");
let randomWordsArr16 = randomWords16.split("#");
let randomWordsArr17 = randomWords17.split("#");
let randomWordsArr18 = randomWords18.split("#");
let randomWordsArr19 = randomWords19.split("#");
let randomWordsArr20 = randomWords20.split("#");
let randomWordsArr21 = randomWords21.split("#");
let randomWordsArr22 = randomWords22.split("#");
let randomWordsArr23 = randomWords23.split("#");
let randomWordsArr24 = randomWords24.split("#");
let randomWordsArr25 = randomWords25.split("#");
let randomWordsArr26 = randomWords26.split("#");
let randomWordsArr27 = randomWords27.split("#");
let totalRandArr1 = randomWordsArr1.concat(randomWordsArr2)
let totalRandArr2 = totalRandArr1.concat(randomWordsArr3);
let totalRandArr3 = totalRandArr2.concat(randomWordsArr4);
let totalRandArr4 = totalRandArr3.concat(randomWordsArr5);
let totalRandArr5 = totalRandArr4.concat(randomWordsArr6);
let totalRandArr6 = totalRandArr5.concat(randomWordsArr7);
let totalRandArr7 = totalRandArr6.concat(randomWordsArr8);
let totalRandArr8 = totalRandArr7.concat(randomWordsArr9);
let totalRandArr9 = totalRandArr8.concat(randomWordsArr10);
let totalRandArr10 = totalRandArr9.concat(randomWordsArr11);
let totalRandArr11 = totalRandArr10.concat(randomWordsArr12);
let totalRandArr12 = totalRandArr11.concat(randomWordsArr13);
let totalRandArr13 = totalRandArr12.concat(randomWordsArr14);
let totalRandArr14 = totalRandArr13.concat(randomWordsArr15);
let totalRandArr15 = totalRandArr14.concat(randomWordsArr16);
let totalRandArr16 = totalRandArr15.concat(randomWordsArr17);
let totalRandArr17 = totalRandArr16.concat(randomWordsArr18);
let totalRandArr18 = totalRandArr17.concat(randomWordsArr19);
let totalRandArr19 = totalRandArr18.concat(randomWordsArr20);
let totalRandArr20 = totalRandArr19.concat(randomWordsArr21);
let totalRandArr21 = totalRandArr20.concat(randomWordsArr22);
let totalRandArr22 = totalRandArr21.concat(randomWordsArr23);
let totalRandArr23 = totalRandArr22.concat(randomWordsArr24);
let totalRandArr24 = totalRandArr23.concat(randomWordsArr25);
let totalRandArr25 = totalRandArr24.concat(randomWordsArr26);
let totalRandArr26 = totalRandArr25.concat(randomWordsArr27);

let textBox = document.getElementById("demo");

function putRandomWord() {
    textBox.innerHTML = totalRandArr26[Math.floor(Math.random() * 4450)];
}



